xenia-project/xenia

src/poly/logging.cc

Add a missing include in logging.cc that fixes the missing definition for
thread_local. Similar to issue #122.

libpoly: add missing include for thread_local define in logging.cc

---

src/xenia/xenia_main.cc

Fixes usage when running with a single unnamed argument - the alternative is to enforce gflags

Minor usage fix

---

src/xenia/kernel/fs/devices/host_path_device.cc

New paths can now be created if they do not exist - this allows content packages such as savedata to be written to disk

Fixed writing data to the host device

---

CONTRIBUTORS.md
src/xenia/kernel/fs/devices/stfs_container_device.cc
src/xenia/kernel/xam_module.cc
src/xenia/kernel/xam_module.h
src/xenia/kernel/xboxkrnl_module.cc
src/xenia/kernel/xboxkrnl_module.h
src/xenia/kernel/xobject.cc
src/xenia/tools/api-scanner/README.md
src/xenia/tools/api-scanner/api_scanner_loader.cc
src/xenia/tools/api-scanner/api_scanner_loader.h
src/xenia/tools/api-scanner/api_scanner_main.cc
src/xenia/tools/api-scanner/sources.gypi
xenia.gyp

New tool for issue #171 which links to libxenia to dump the API usage from packaged content.
Summary
* Registering XKernelModule tables has been partially moved into a static 'RegisterExportTable'
* Due to XObject usage without a kernel state, added some checks for nullptr to support basic usage
* Also commented out the STFS container dumping by default

Added API scanner tool

---

src/xenia/cpu/backend/x64/x64_emitter.cc
src/xenia/cpu/backend/x64/x64_emitter.h
src/xenia/cpu/backend/x64/x64_sequences.cc
xenia.gyp

Added code to dynamically select which instructions to use at runtime based on the host's CPU
I've ran the tests in xe-cpu-ppc-test, they've all passed except for the ones I still haven't replaced.

Replace some instructions for CPUs without AVX2/CNTLZ

---

src/xenia/base/logging.cc
src/xenia/gpu/gl4/gl4_shader.cc
src/xenia/gpu/gl4/gl_context.cc

Revert commits 6d159dc2 and 3f480d24. Visual Studio 2013 is not
supported anymore, so they are not needed.

Remove cxx_compat.h header

---

src/xenia/apu/audio_decoder.cc
src/xenia/apu/audio_decoder.h
src/xenia/apu/audio_system.cc
src/xenia/apu/audio_system.h

- Fixes decoder accidentally clamping audio to half its original volume
- Select XMA buffer 1 if necessary (although it can't decode buffer 1 at all)
- Asserts if buffer 1 is not NULL (game will stop waiting for the decoder if it isn't)
- context.kicked flag so the decoder only picks contexts that the game wants to be decoded.

More Audio Fixes

---

src/xenia/gpu/gl4/blitter.cc
src/xenia/gpu/gl4/gl4_profiler_display.cc
src/xenia/gpu/gl4/gl4_shader.cc

These three commits are to fix some issues seen when trying to run on AMD video cards. For reference, this is Catalyst 15.200.1018 on Win8.1.
It's not perfect as there is still OpenGL errors being thrown, but at least the profiler display works now.
For the structs as in/out, there are still some present in command_processor.cc and gl4_shader.cc, but no errors are being thrown?? I guess we'll see if those parts will need to change too.

Fixes some issues on AMD drivers

---

src/xenia/base/debugging.h
src/xenia/base/debugging_win.cc
src/xenia/cpu/backend/x64/x64_emitter.cc

* Protected with a flag w/ default of false, since logging to debugger is apparently super duper slow

Log DebugPrint traps to debugger

---

src/xenia/gpu/gl4/command_processor.cc

While trying to debug an OpenGL error on AMD, I found out that the following was logged in the pipeline infolog after a validation of the pipeline:
in_vtx.o[0]'s data type or qualifiers doesn't match between vertex shader and geometry shader
draw_id's data type or qualifiers doesn't match between geometry shader and fragment shader
Basically, as described in the commit message, the Geometry shader has the wrong layout value for its VertexData input/output, compared to the Vertex and Pixel shaders.
Unfortunately, this does not fix the error I was debugging...
Also, this should probably be tested before merging by someone who can display something (i.e. someone with a nVidia card), to make sure it still works. I was not able to, for obvious reasons...

gl4: command_processor: fix locations in geometry shader header

---

src/xenia/gpu/gl4/command_processor.cc

Tested with RR 6 (w/ forcing depth_color_enabled)

gl4 : clear depth and stencil seperately using the DSA version

---

src/xenia/gpu/gl4/gl_context.cc

When there is no vendor specific info, there is no space. Fixes a crash when that happens.

gl4: fix glsl version detection when there is no vendor specific info

---

libxenia.vcxproj
libxenia.vcxproj.filters
vsdebuggervis.natvis

* xe::be supported by debugger now
* Doesn't support 8-byte conversions right now, but should be easy to add.

Add VS debugger visualization file

---

src/xenia/base/byte_order.h
src/xenia/cpu/xex_module.cc
src/xenia/cpu/xex_module.h
src/xenia/kernel/kernel_state.cc
src/xenia/kernel/objects/xthread.cc
src/xenia/kernel/objects/xuser_module.cc
src/xenia/kernel/objects/xuser_module.h
src/xenia/kernel/util/xex2.cc
src/xenia/kernel/util/xex2.h
src/xenia/kernel/util/xex2_info.h
src/xenia/kernel/xboxkrnl_modules.cc
src/xenia/kernel/xboxkrnl_threading.cc

* Removes most dependencies on xex2.c/.h
* Stores the xex2 header in host(XexModule) and guest(XUserModule) memory for direct access
* Added a bunch of structs for direct access to xex2 headers
* If an import function is unresolved, rewrite the thunk to trigger a PPC trap and return to caller.
* Bad things:
* Due to the way we're now resolving imports, we can't dump them to debug out anymore (except when loading the module). Should be fine though, the loading code will warn if importing an unimplemented variable/function.

XEX2 Code Refactoring

---

src/xenia/cpu/frontend/ppc_emit_alu.cc

Looks like there are no xori , xoris and oris ppc test .
http://build.xenia.jp/builders/pull-request-builds/builds/72/steps/ppc%20test%20(haswell)/logs/stdio

alu: use XEEXTZ16 for uimm16

---

src/xenia/kernel/object_table.cc
src/xenia/kernel/object_table.h
src/xenia/kernel/objects/xthread.cc
src/xenia/kernel/xboxkrnl_ob.cc
src/xenia/kernel/xobject.cc
src/xenia/kernel/xobject.h

* Should fix games that use NtClose like they're supposed to (such as xenia-project/game-compatibility#99)

Track object handle reference counts in the object table.

---

src/xenia/base/threading.h
src/xenia/base/threading_win.cc
src/xenia/kernel/objects/xthread.cc
src/xenia/kernel/objects/xthread.h

* Allows us to easily match XThreads in the VS debugger to lines in the log

Include host ID in XThread names

---

src/xenia/memory.cc

I put RFC because I am not sure if it's the proper way to fix this.
Some games appear to try to manually find the biggest chunk of memory they can get their hands on by repetitively calling MmAllocatePhysicalMemoryEx (and the associated free when the allocation succeeds).
Problem is that they start with an impossible size (1GB), as follows:
`d> 2970 MmAllocatePhysicalMemoryEx(0, 3FFFFFFF, 20000004, 00000000, FFFFFFFF, 00010000)`
This causes a memory acces violation crash in BaseHeap::AllocRange because we are out of range in page_table_. Make sure this doesn't happen by checking beforehand that the page count can fit in the requested page range.
The games that do this will hit the assert at https://github.com/benvanik/xenia/blob/master/src/xenia/memory.cc#L696 but they can continue …

[RFC] Fix crash when some games request too much memory

---

src/xenia/hid/winkey/premake5.lua
src/xenia/hid/winkey/winkey_input_driver.cc
src/xenia/hid/winkey/winkey_input_driver.h
src/xenia/ui/ui_event.h
src/xenia/ui/window_win.cc

* GetKeystroke now depends on WM messages
* GetState no longer acts when Xenia's not in focus.

Winkey fixes

---

src/xenia/cpu/frontend/ppc_emit_control.cc

* This is a no-op because Xenia doesn't support context switching.

Don't assert on VRSAVE mfspr/mtspr (used by gcc)

---

src/xenia/cpu/mmio_handler.cc
src/xenia/cpu/mmio_handler.h
src/xenia/memory.cc

* Should prevent the MMIO handler double-crashing Xenia in an already invalid state.

Fix the MMIO handler picking up invalid accesses outside of the mapped range

---

src/xenia/base/exception_handler.h
src/xenia/base/exception_handler_win.cc
src/xenia/emulator.cc
src/xenia/emulator.h

* Should allow end users to differentiate between host/guest crashes easier.
* Allows developers to attach a debugger after Xenia crashes.

Pause Xenia if it crashes in guest code

---

building.md
src/xenia/cpu/elf_module.h
xenia-build

Specify Clang 3.8 for building under Linux. Fix a build error due to upgrading. Finally, update the Linux section of building.md. As mentionned, we can't build with GCC right now because Clang specific "no-error" flags are used. I guess compiler specific flags should be added in premake files.

Use Clang 3.8 for Linux build.

---

src/xenia/vfs/devices/disc_image_device.cc

Tested with Skyrim's DISC1 ISO. It doesn't load otherwise.
(Submitting this through github's web editor)

Add another likely offset for ISO magic

---

src/xenia/cpu/frontend/ppc_emit_control.cc

While the instruction `mtocrf` only allows to update one CR field at a time, the instruction `mtcrf` allows a subset of CR fields to be updated. However, Xenia's implementation of `mtcrf` updates all fields, ignoring the `FXM` instruction code. Only `mtcr rS` (simplified mnemonic for `mtcrf 0xFF, rS`) does that.
PS: See page 130 in the [Power ISA docs](https://www.power.org/wp-content/uploads/2012/07/PowerISA_V2.06B_V2_PUBLIC.pdf).
PSS: Since this is a small change, I haven't bothered to build Xenia, let alone running tests before submitting this PR.

Fixed mtcrf which was wrongly implemented as mtcr

---

src/xenia/cpu/mmio_handler.cc
src/xenia/cpu/mmio_handler.h
src/xenia/memory.cc

* Fixes: *Everything*
* Games were freeing texture memory and then reallocating texture memory in the same spot, which neutered the MMIO Handler's watching capabilities. We now purge the entry when the memory is freed or its access protection is changed.

Texture Invalidation Fix

---

src/xenia/kernel/xam/user_profile.cc
src/xenia/kernel/xam/xam_user.cc

Handles writing binary blob settings to the user profile which can then be read
by XamUserReadProfileSettings.
This allows the game "Legend of Spyro: Dawn of the Dragon" to proceed past its "press start" screen. It would otherwise sit in an infinite loop calling XamUserWriteProfileSettings to write some config data and XamUserReadProfileSettings to verify the write.
The implementation is definitely not complete since it's based on observing the behaviour of only one game. That game only writes the BINARY type, so I wasn't able to deduce the format of any of the other datatypes from the structs that it passes to this function.

Partially implement XamUserWriteProfileSettings

---

src/xenia/ui/gl/blitter.cc

* Fixes color copies between two textures with mismatching swizzle parameters.
* Fixes color issues in Banjo Kazooie / Banjo Tooie (xenia-project/game-compatibility#206 / xenia-project/game-compatibility#207)

Color Copy Fix

---

src/xenia/gpu/command_processor.cc
src/xenia/gpu/command_processor.h

I've added this opcode based upon what I assume is the proper implementation of it assuming it's name is a proper descriptor of what it does.
Arguments should be a register and a memory address. Swapping the arguments throws an out of range exception on the register side.
I've been sitting on this for a while, just figured that it might be the proper implementation. I could be totally wrong however.

Implemented REG_TO_MEM GPU opcode

---

src/xenia/gpu/trace_player.cc
src/xenia/gpu/trace_player.h
src/xenia/gpu/trace_viewer.cc

* Allow seeking forward more than one frame (without playing from the beginning)
* Progress bar while seeking
* Fixes crash with texture view open while seeking (masks it really - but that should be fine. See https://github.com/benvanik/xenia/commit/7a1d7bd652c1fc5d533a7e4cb532003fa141efe5)
* Disable command list and frame list UI while playing back a trace (to avoid queuing up a crapload of commands)

Trace Viewer UI Improvements

---

src/xenia/cpu/compiler/passes/constant_propagation_pass.cc
src/xenia/cpu/hir/value.cc
src/xenia/cpu/xex_module.cc

* Fix double-swapping in OPCODE_LOAD
* Add code to enforce page protections (but commented because it introduces a load of constants)

Compiler fixes

---

src/xenia/debug/ui/debug_window.cc
src/xenia/ui/gl/gl_context.cc
src/xenia/ui/gl/gl_context.h

Installed VS2015U1, fixed compilation. Similar fix to commit 08ae855.
Also, dc_ can be used directly right? Is the dc() function a relic of some older and deleted code? Anyway, I removed it.
Thanks!

VS2015 Update 1 fix + GLContext small cleanup

---

src/xenia/gpu/glsl_shader_translator.cc

Comparison of uvec2 and int is not possible, explicitly
use a zero-value uvec2.
Error from logs:
```
!> 00000004 Unable to link program: 
Shader Compile Log:
Fragment shader failed to compile with the following errors:
ERROR: 0:125: error(#162) Wrong operand types: no operation "!=" exists that takes a left-hand operand of type "const in highp 2-component vector of uvec2" and a right operand of type "const int" (or there is no acceptable conversion)
ERROR: error(#273) 1 compilation errors.  No code generated
```
Example line: [see line 125 of full shader here](https://gist.github.com/sephiroth99/53b8a9087e8be1bc8424) This example shader is from Forza 2.
```
if (state.texture_samplers[0] != 0) {
```

Fix compilation error of translated GLSL shader.

---

src/xenia/kernel/util/object_table.cc
src/xenia/kernel/util/object_table.h

Function template 'LookupObject' in ObjectTable class has
a specialization in class scope, which is not allowed.
While MSVC seems OK with that, clang complains about it.
Fix this issue by moving the definition of the specialisation
outside the class scope, and moving the declaration in the
'.cc' file.
See previous discussion in #482.

ObjectTable: Remove explicit specialization in class scope

---

src/xenia/gpu/gl4/gl4_command_processor.cc
src/xenia/gpu/gl4/gl4_shader.cc
src/xenia/gpu/glsl_shader_translator.cc
src/xenia/gpu/trace_player.cc
src/xenia/ui/gl/blitter.cc
src/xenia/ui/gl/gl_context.cc
src/xenia/ui/gl/gl_context.h
src/xenia/ui/graphics_context.h

* Shaders:
* Fix incorrect compare against bool consts
* Always output the info log if it isn't empty (for shader warnings)
* GL backend:
* Setup to allow Xenia to detect a graphics TDR on contexts
* TODO: Dump the command stream on TDR.
* Minor: Blitter::Draw asserts if src_texture is 0.

GL Backend Changes/Fixes

---

src/xenia/base/bit_map.h
src/xenia/base/byte_stream.cc
src/xenia/base/byte_stream.h
src/xenia/base/profiling.cc
src/xenia/cpu/hir/value.cc
src/xenia/cpu/processor.cc
src/xenia/debug/ui/debug_window.cc
src/xenia/emulator.cc
src/xenia/gpu/glsl_shader_translator.cc
src/xenia/gpu/shader.cc
src/xenia/gpu/shader_translator.cc
src/xenia/gpu/shader_translator_disasm.cc
src/xenia/ui/imgui_drawer.cc
src/xenia/ui/window.cc

Ran the ol' clang again. These fixes are pretty simple so they should not cause any problem. Almost half of it is to handle all enum values in switch-cases. Compiled on Windows and Linux, quick test on Windows.
There is more to come, I'm stubbing the code along so clang can eventually compile all of Xenia.

Fix various clang compilation issues 

---

src/xenia/cpu/xex_module.cc
src/xenia/kernel/user_module.cc
src/xenia/kernel/util/xex2.cc

Found with Astropop (xenia-project/game-compatibility/issues/2).
The library name indexes are `0xCD00` and `0xCD01` which were masked to 8-bits in the previous implementation (https://github.com/benvanik/xenia/blob/ea99ba8e3bbac03386c95efe1496d5f4b03f5456/src/xenia/kernel/util/xex2.cc#L272).
I opted to just cap the index by the number of libraries. If there is a hard limit of 255 imports then the `xe_xex2_import_library_t` will need changing :smile:

Fixed rare crash when accessing library import by name

---

premake5.lua
src/xenia/app/emulator_window.cc
src/xenia/app/emulator_window.h
src/xenia/app/premake5.lua
src/xenia/app/xenia_main.cc
src/xenia/cpu/xex_module.cc
src/xenia/emulator.cc
src/xenia/emulator.h
src/xenia/kernel/kernel_module.cc
src/xenia/kernel/user_module.cc
src/xenia/ui/window.h
src/xenia/ui/window_win.cc
src/xenia/ui/window_win.h
src/xenia/xdbf/premake5.lua
src/xenia/xdbf/xdbf_utils.cc
src/xenia/xdbf/xdbf_utils.h

Replaces window title and icon with the resources in the current module - part of #506 
Example:

Rebrand the Xenia window with module metadata

---

src/xenia/base/profiling.cc
src/xenia/base/threading.cc
src/xenia/base/threading_win.cc
src/xenia/cpu/backend/x64/x64_emitter.cc
src/xenia/cpu/hir/value.cc
src/xenia/cpu/testing/vector_max_test.cc
src/xenia/cpu/testing/vector_min_test.cc
src/xenia/gpu/gl4/gl4_shader.h
src/xenia/kernel/xboxkrnl/xboxkrnl_rtl.cc
src/xenia/kernel/xthread.cc
tools/build/scripts/build_paths.lua

Some small fixes for compilation under Clang. There are two bigger fixes:
1- Using 'hardware_concurrency': implements logical_processor_count for all platforms. On my i5 it reported all the cores, I don't have an i7 with hyper threading to test.
2- Reworking RtlTime: uses C library functions in order to be portable. Tested with Minecraft game, at startup it does some conversions and the results are the same.
Thanks!

Linux compilation/link and compatibility fixes

---

src/xenia/gpu/glsl_shader_translator.cc
src/xenia/ui/gl/gl_context.cc

2 things:
1- minor syntax fix
2- changes from commit f75a4cab0e2ec6d7acde47bea38fbd994994ac54 introduced usage of ```mix(vec4, vec4, bool)``` which is a GLSL 4.50 function. The shaders do not compile on AMD anymore, so make it a failure to not support GLSL 4.50 (like it was before). Also, this probably means that issue #416 is not caused by incomplete GLSL support...

More shader changes

---

src/xenia/base/profiling.cc
src/xenia/base/profiling.h
src/xenia/gpu/command_processor.cc

* Makes moving the mouse around on-screen not start a new profiler frame

Decouple MicroProfilerFlip from Profiler::Present

---

src/xenia/gpu/trace_viewer.cc
src/xenia/ui/gl/gl_immediate_drawer.cc
src/xenia/ui/gl/gl_immediate_drawer.h
src/xenia/ui/imgui_drawer.cc
src/xenia/ui/imgui_drawer.h
src/xenia/ui/immediate_drawer.h

* Zoomed views for color targets / depth targets
* Fixes invisible images due to their alpha.
* Also correctly flags the alpha test as disabled/enabled

Trace Viewer Zoomed View / Fix Alpha Test

---

src/xenia/gpu/glsl_shader_translator.cc

The boolean value must be a vector too, where each bool component
selects whether the value of the output vector component is from the
first or the second source vector.

Fix usage of mix in fragment shader

---

src/xenia/base/vec128.h
src/xenia/cpu/hir/value.cc

Added double precision (f64) values to the vec128 structure
Added cases for all formats of data for vector subtraction in the
Value::VectorSub function
NOTE: Unsure what the saturate function is for however maintained
original functionality

Expanded vec128 and VectorSub

---

src/xenia/gpu/shader.cc

Use binary mode when writing shaders to file, so that 0x0a is not
considered a LF and then converted to CRLF.

Dump shaders in binary mode

---

docs/style_guide.md

A few of the links pointing to Google's cpp style guide were pointing to dead pages where the old Google code project was. The project has since switched to Github and hosts itself as html pages. This commit updates the references to point to the new urls.

Fix dead links to Google style guide

---

src/xenia/kernel/util/shim_utils.h
src/xenia/kernel/xboxkrnl/xboxkrnl_ob.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_rtl.cc

Progress on #631
I'm pretty sure these changes are correct, although what could be helpful in the future is unit testing all these kernel exports to make sure there aren't regressions. Or maybe there is a list somewhere of which games use which exports so I can do some cursory checks?

Update kernel convention for xboxkrnl_rtl.cc, xboxkrnl_ob.cc

---

third_party/vulkan/loader/premake5.lua

* Remove Win32 dirent implementation from Linux build
* Fix a bunch of clang warnings
* Add default paths that would otherwise be passed from CMake

third_party: vulkan: loader: fix Linux build

---

src/xenia/cpu/compiler/passes/constant_propagation_pass.cc
src/xenia/gpu/command_processor.cc
src/xenia/gpu/spirv_shader_translator.cc
src/xenia/gpu/spirv_shader_translator.h
src/xenia/gpu/texture_info.cc
src/xenia/gpu/trace_viewer.cc
third_party/llvm/include/llvm/Support/MathExtras.h

* Fixed missing includes (cmath, cfloat)
* Added const specifiers to some functions in SPIR-V builder so there aren't any lvalue-references to temporary objects in spirv_shader_translator
* Fixed crossed variable initialization
* xb format did quite a few changes
FTR I was building with clang 3.8.0 on Fedora 25

Linux + clang build fixes

---

src/xenia/vfs/devices/disc_image_device.cc
src/xenia/vfs/devices/stfs_container_device.cc

vfx::Entry originated from filesystem_win.cc holds file time fields in FILETIME format (100-nanosecond intervals since January 1, 1601), while StfsContainerDevice provides UNIX epoch time (or something close to that), and DiscImageDevice just sets it to zero. This leads RtlTimeToTimeFields  to crash later.
This can be fixed in filesystem_win.cc and NtQueryFullAttributesFile/NtQueryFullAttributesFile, but this place seems to be a better fit.
I have it tested on two games only (both were crashing before), so it would be nice for someone to try some more discs/images.

Make vfs::Entry time stamps consistent (as Windows FILETIME)

---

src/xenia/kernel/xboxkrnl/xboxkrnl_module.cc

Depending on the link order, static object xboxkrnl_exports could be not initialized yet (have zero size) when DECLARE_XBOXKRNL_EXPORT is called.

* statics initialization order fix

---

src/xenia/gpu/command_processor.cc
src/xenia/gpu/vulkan/pipeline_cache.cc

Must reset read_ptr_index_ in CommandProcessor::InitializeRingBuffer becaue a game can initialize the ring buffer multiple times.
Left the new condition on the assertion as the value 0xFFFFFF seems to acceptable and it's preventing 4B4F07FE to go ahead.

Ringbuffer init fix

---

src/xenia/cpu/ppc/ppc_emit_altivec.cc

As per analysis at https://github.com/xenia-project/game-compatibility/issues/735 we need to recalculate ea and eb after the block ends and a new one begin.

Fixing Altivec lvrx and stvrx

---

xenia-build

Otherwise it breaks on Arch Linux

Specify python2 in xenia-build

---

src/xenia/kernel/xboxkrnl/xboxkrnl_threading.cc

We have found and fixed a bug using [PVS-Studio](https://www.viva64.com/en/pvs-studio/) analyzer. 
Return the variable _old_head_, which is always zero.
Analyzer warning: V561 It's probably better to assign value to 'old_head' variable than to declare it anew. Previous declaration: xboxkrnl_threading.cc, line 1256.

xboxkrnl_threading.cc: PVS-Studio: fixed return value.

---

src/xenia/base/bit_stream.cc

PVS Studio found error //V629 32-bit value with a subsequent expansion to the 64-bit type

32-bit value fix to the 64-bit type.

---

third_party/clang-format/LICENSE.TXT
third_party/clang-format/clang-format-bbedit.applescript
third_party/clang-format/clang-format-diff.py
third_party/clang-format/clang-format.el
third_party/clang-format/clang-format.py
third_party/clang-format/git-clang-format

This commit updates clang-format to the newest version, this adds support for Python 3 in clang-format. It also adds the plugin files for Emacs, Vim and BBEdit.
I also added the LICENSE.txt because it's required by the license.

clang-format update and addition

---

src/xenia/gpu/vulkan/texture_cache.cc

It turns out the wrong color format for DXT caused this issue.
Before:
After:
The water reflection is still incorrect, will look into that later.

Fixed Vulkan's dark color issue.

---

src/xenia/gpu/vulkan/texture_cache.cc

Set borderColor to transparent to get rid of white edges on some textures(mainly text).
Before:
After:

Fixed white edge on some textures(text display).

---

src/xenia/app/emulator_window.cc
src/xenia/app/xenia_main.cc
src/xenia/emulator.cc
src/xenia/ui/menu_item.h
src/xenia/ui/window.h
src/xenia/ui/window_win.cc
src/xenia/ui/window_win.h

The menu bar on the main window is now greyed out until the emulator is completely initialized.
This is a slightly hacky fix, it would probably be better to make the dependency between the emulator and the window one-way so a proper wait can be done during the initialization phase. However, currently they are both pretty entangled so I'm not sure that'd be worth doing until Xenia has a more permanent UI.
Fixes issue #702

Prevent race condition during emulator startup (issue #702)

---

src/xenia/ui/gl/gl_context.cc

This change allows Xenia to detect if the system has OpenGL 4.6

Detect OpenGL 4.60

---

premake5.lua

Thanks to @yxmline from #812 
As someone with a Japanese copy of Windows, I need this change to build the project.

Allow computers with non-latin native codepages to build the project.

---

src/xenia/ui/vulkan/vulkan_context.cc

This prevents the graphics context from being constantly recreated on HiDPI systems. The window resize check was not using the scaled window dimensions so the context was recreated on every frame as the dimensions were always different.

UI/Vulkan: Fixed graphics context recreation on HiDPI systems

---

docs/building.md

VS2015 comes with the Windows Universal CRT SDK by default however VS2017 needs to have it manually added.
The Windows 8.1 SDK is required when building on both Windows 8.X and 10.
Python 3.4+ is now required to run the setup scripts.

Actually fix building.md

---

src/xenia/cpu/backend/x64/x64_emitter.cc
src/xenia/cpu/backend/x64/x64_emitter.h
src/xenia/cpu/backend/x64/x64_sequences.cc

Fix for d61aff438923fb81fd875c9a5fb99a2d423e7cf9 that caused tests to fail.

[CPU] Bring back saturation in D3DCOLOR vpkd3d128

---

src/xenia/emulator.cc

Call of Duty 4 and World at War alphas have .exe files like CoD3SP.exe and CoD3SP_profile.exe alongside default.xex that are actually XEX files.

[Core] Treat .exe files as XEX

---

src/xenia/gpu/vulkan/pipeline_cache.cc
src/xenia/gpu/vulkan/pipeline_cache.h

Fixes Z fighting of decals in various games including the Call of Duty series, and possibly shadow acne in some games also.
Since the registers contain offset values for both polygon sides, the actual value is chosen based on the culled side (if none are culled, then choosing the side that has any offset, if both have, using the front). However, I doubt different values for different sides are even exposed via D3D at all, but who knows what games do.
I'm not sure what we should prefer — enable depth offset in all Vulkan pipelines, or toggle based on the actual state. However, it's usually enabled for a small portion of drawn surfaces, and those surfaces already have their own pipelines generally, so I think the second option, implemented here, is better.

[GPU] Depth bias support

---

src/xenia/gpu/xenos.h

A small documentation update — actually handling those would be much more complicated. Adds the possible values of sign_x/y/z/w in texture fetch constants.
`UnsignedBiased` should be very easy to handle in shaders, `Gamma` can be handled in shaders too, but `Signed` would require two image descriptors to be bound and sampled — one for the UNORM/UINT view of the texture and another for the SNORM/SINT one — because there are formats like `D3DFMT_X8L8V8U8` that contain both signed and unsigned data.

[GPU] Add texture signedness enumeration

---

xenia-build

Match xenia-build and premake configuration and platform capitalization with
only first letter capitalized in filesystem (Debug, Checked, Released, Linux,
Windows, etc).
Fix xenia-build test command on linux systems.
The issue in question arises because `get_bin()` returns `None` if it cannot find the file in question and it searches for ".../build/bin/linux/debug/xenia-cpu-ppc-tests" instead of ".../build/bin/Linux/Debug/xenia-cpu-ppc-tests'" with capitals on both "Debug" and "Linux"
```
./xenia-build test
Testing...
Traceback (most recent call last):
File "./xenia-build", line 1351, in <module>
main()
File "./xenia-build", line 81, in main
return_code = command.execute(args, pass_args, os.getcwd())
File "./xenia-build", line 794, in execute
if not has_bin(test_executable):
File …
```

[Test] Fix build_bin_path for case sensitive FS

---

src/xenia/kernel/xam/apps/xmp_app.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_strings.cc

This fixes _snwprintf not having format_core's wide param as true, without this dash.xex was failing to create proper locator strings, but with the fix the strings were being made fine, so I think this is how _snwprintf was meant to work. It might still be worth checking any other titles that use it though.
Also adds some null pointer checks to the handlers inside xmp_app.cc, 1888 dash.xex was calling them without the pointers being set which resulted in a crash, this could be due to 1888 dash/xam using different XMP structs.. hopefully not, but for now this stops the crashing at least.

[Kernel] Fixes for _snwprintf and xmp_app

---

src/xenia/cpu/xex_module.cc
src/xenia/cpu/xex_module.h
src/xenia/kernel/user_module.cc
src/xenia/kernel/util/xex2_info.h

Oops - forgot to byteswap the xex2_page_descriptor struct when it's used in FindSaveRest, this was causing it to not find any save/rest functions, which would make Skate 3 crash on boot, and ODST crash before the menu is shown. (both worked fine pre-xexp merge)
Also fixed up the xex2_page_descriptor struct to be more descriptive (which is why other files had to be modified besides just xex_module.cc)
Tested Skate 3 with the fix and it now loads up fine, ODST seems to load to the menu now too (but since it doesn't draw anything in VK I could only tell by the sound)

[CPU] Fix XexModule::FindSaveRest not finding functions properly

---

src/xenia/kernel/xam/xam_content.cc
src/xenia/kernel/xenumerator.cc
src/xenia/kernel/xenumerator.h

Like said in #1255, it seems the limit passed to XamContentCreateEnumerator is actually a limit on how many results XamEnumerate should return per call, not a limit on the number of enumeration items in total.
These changes will fix Sonic Unleashed not loading more than 1 DLC (it passes 1 as the limit, but then loops over XamEnumerate to load in each DLC one at a time), and likely many other games.
Other enumerators like XamContentCreateDeviceEnumerator also seem to work the same way on 360, so hopefully they should also work fine once added to Xenia.

[Kernel] Remove item limit from enumerators, fixes #1255

---

src/xenia/kernel/xboxkrnl/xboxkrnl_debug.cc

Some games pass nullptrs in to SetThreadName, causing crashes. Dark Souls 2 goes from crashing on startup to ingame with this change.

don't dereference null pointers in SetThreadName

---

src/xenia/cpu/stack_walker.h
src/xenia/kernel/xam/app_manager.h

Made xe::kernel::App and xe::cpu::StackWalker destructors virtual, since they are abstract classes.
This fixes build the following build errors on Linux:
```
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/unique_ptr.h:78:2: error: delete called on
'xe::kernel::xam::App' that is abstract but has non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
delete __ptr;
^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/unique_ptr.h:78:2: error: delete called on
'xe::cpu::StackWalker' that is abstract but has non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
delete __ptr;
^ 
```

Fix Linux Build Errors By Adding Virtual Destructors to Abstract Classes

---

src/xenia/kernel/xam/content_manager.cc
src/xenia/kernel/xam/content_manager.h
src/xenia/kernel/xam/user_profile.cc
src/xenia/kernel/xam/user_profile.h
src/xenia/kernel/xam/xam_user.cc

Save and load title-specific profile content to disk in the content folder for that title.  Allows saving settings for many games and saving games for games that store saved games there, such as BattleBlock Theater.

Persist title-specific profile content

---

premake5.lua

The premake config doesn't include the debug symbols on linux in the debug config this adds them.
Commit cherry-picked from #1076.

Add debug symbols when building Debug on linux

---

src/xenia/base/filesystem.h
src/xenia/base/filesystem_win.cc
src/xenia/vfs/devices/stfs_container_device.cc
src/xenia/vfs/devices/stfs_container_device.h
src/xenia/vfs/devices/stfs_container_entry.cc
src/xenia/vfs/devices/stfs_container_entry.h
src/xenia/vfs/devices/stfs_container_file.cc

Tested on several GoD container and XBLA Games (Burnout Revenge, Halo 3, Halo 3 ODST, JUJU, Duke Nukem 3D). Diff'ed various container files from the original source with no discrepancies. Handles both GDF and non-GDF formats with the same functions.

Games on Demand / Multi-file STFS (SVOD) Support

---

src/xenia/app/xenia_main.cc
src/xenia/base/filesystem_posix.cc
src/xenia/base/string.cc

per #399 , these lines were only required because codecvt was missing in GCC. That has since been fixed per https://stackoverflow.com/questions/15615136/is-codecvt-not-a-std-header

[Base] Remove hacky fix for missing codecvt on linux

---

src/xenia/base/logging.cc

We manually call the logger destructor when a fatal error occurs, this fixes the error not showing up in the log file when a fatal error is triggered

Flush the logger before exiting on a fatal error

---

src/xenia/kernel/xboxkrnl/xboxkrnl_ob.cc

Adds ObReferenceObjectByName to xboxkrnl_ob.cc, this is used by the XEFU Xbox OG emu and required for it to progress.
This seems to be a working impl for it, though two of the args for it go unused (attributes & parse_context), we don't seem to handle those in any other Ob* funcs though so I guess it's fine for now.

[Kernel] Add ObReferenceObjectByName

---

src/xenia/cpu/ppc/ppc_opcode_disasm.cc

Add extended mnemonics of BC instruction for the disassmebler.
How it looks:

ppc disasm: BC formatting improvements

---

xenia-build

This PR modifies xenia-build to pass an additional `-utf8` parameter to `vswhere.exe`. This fixes `xb` command on systems where a JSON file procuded by this tool contains regional characters. Well formed JSON files are supposed to be in UTF-8, and on top of that Python also expects encoding to be UTF-8, it seems.
This fixes my particular case, where `"description"` field contained strings in Polish (even though both my Windows and VS are in English...) and regional diacritics could not be parsed:
```
H:\dev\emulators\xenia>xb setup
Traceback (most recent call last):
File "xenia-build", line 1366, in <module>
main()
File "xenia-build", line 47, in main
vs_version = import_vs_environment()
File "xenia-build", line 99, in import_vs_environment
vswhere = …
```

[xenia-build] Make vswhere.exe output in UTF-8

---

src/xenia/cpu/lzx.cc

This minor change should fix some problematic patches which would cause "match offset beyond LZX stream" mspack errors.
Tested with Band of Bugs & Perfect Dark which both failed to apply any XEXP previously, now seem working with this fix.

[CPU] Use window size for LZX ref_data_size, fixes some problematic XEXP patches

---

xenia-build

Reasons to merge:
* One-line change
* Generates noise™

Fix typo in xenia-build

---

src/xenia/kernel/xam/xam_ui.cc
src/xenia/kernel/xnotifylistener.cc
src/xenia/kernel/xnotifylistener.h

It seems both Project Sylpheed & Sonic Unleashed require seeing ```XN_SYS_UI = true```, eventually followed by ```XN_SYS_UI = false```, for the game to realise all system UIs are closed, but ATM adding a notification that already exists (before the game gets a chance to dequeue it) will just overwrite the older notifications value, stopping the game from ever getting to see the older notification.
To accommodate sending the two notifications to those games I've changed XNotifyListener::notifications_ to a std::vector instead, allowing for multiple notifications to share the same ID, which should let the game see both XN_SYS_UI notifications instead of just the later XN_SYS_UI = false one.
(it seems my older threaded-xoverlapped stuff could workaround this issue as I guess the game would …

[Kernel] Make XamShow*UI exports send XN_SYS_UI notifications, & small XNotifyListener fix

---

.travis.yml

macOS/OS X support isn't happening any time soon..
Add periods to the end of sentences in documentation for consistency, and remove empty spaces.
clang/llvm-8 wasn't used due to requiring libav to be rebased.

[Travis] Use newer clang+llvm and libvulkan, remove outdated comments

---

.appveyor.yml

Changes:
* Removed unneeded/unused stuff:
* Comments
* `clone_folder` (it defaults to `c:\dev\xenia` anyway)
* environment variables (leftovers from example yml)
* `cmd: set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%` in `install`
* `.bat` after`xb`
* Put `after_build` in proper order and made it use AppVeyor's multi-line syntax.

Clean up .appveyor.yml

---

README.md
docs/building.md

Part 2 of #1391.
README.md changes:
* Replaces website with wiki link since it's not relevant anymore.
* Make Quickstart into an actual Quickstart and move building+xb instructions to building.md
building.md changes:
* Update/remove outdated information.

[Part 2] Update and move documentation from website to GitHub Wiki

---

src/xenia/kernel/xboxkrnl/xboxkrnl_modules.cc

Adds game_language as a variable in the config file.
I think adding it to the UI is pointless for now, since a new UI is in the works. This at least gives users the possibility to change it without having to compile xenia.

Add game_language as a config variable

---

src/xenia/kernel/xam/xam_content.cc

This at least gives users the possibility to change the license mask without having to compile xenia.

Add license mask as a config variable

---

third_party/clang-format/git-clang-format

…esolved on its own by Python 3.7 (unknown when it's actually resolved) but still good to have this fix.

Fix an issue in git-clang-format that exists with Python 3.4.

---

xb.bat

- Properly check if candidate path exists.
- Quote python path when invoking.

More xb.bat fixes.

---

src/xenia/kernel/xam/apps/xlivebase_app.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_crypt.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc
src/xenia/vfs/devices/host_path_entry.cc
src/xenia/vfs/devices/host_path_entry.h
src/xenia/vfs/entry.h

This adds two functions used by Forza 4 when saving (XeKeysObscureKey & XeKeysAesCbcUsingKey), a stub for an XLiveBase message that it needs to return success, and a fix for the game truncating save files by accident.
The two functions should work pretty much like they do inside the HV, though on X360 they use a per-console key for the obscuring-crypto, I've just set that to an all zero key in Xenia.
The XLiveBase message doesn't seem to write anything to the message buffer, just reads something from it AFAIK. Forza needs it to return success for the profile to be recognised so I've just added a stub for it.
The truncation bug was a tricky one, but I've narrowed it down to how we handle the file size of an XFile.
When writing data to a save, the game uses NtQueryInfoFile to make sure …

[Kernel] Exports & fixes needed for Forza 4 saving/loading

---

src/xenia/cpu/backend/x64/x64_backend.cc
src/xenia/cpu/backend/x64/x64_code_cache.cc
src/xenia/cpu/backend/x64/x64_code_cache.h
src/xenia/cpu/backend/x64/x64_code_cache_win.cc
src/xenia/cpu/backend/x64/x64_emitter.cc
src/xenia/cpu/backend/x64/x64_emitter.h

[x64] Fix up unwind info for emitted functions.
- [x64] Track size of code within emitted functions (prolog, body, epilog).
- [x64] Don't use hardcoded prolog size in generated unwind info.
- [x64] Update URLs to MSDN documentation on `UNWIND_INFO`/`UNWIND_CODE`.

[x64] Unwind fixes.

---

src/xenia/app/xenia_main.cc
src/xenia/base/cvar.cc
src/xenia/base/cvar.h
src/xenia/base/main.h
src/xenia/base/main_posix.cc
src/xenia/base/main_win.cc
src/xenia/cpu/ppc/testing/ppc_testing_main.cc
src/xenia/gpu/shader_compiler_main.cc
src/xenia/gpu/vulkan/vulkan_trace_dump_main.cc
src/xenia/gpu/vulkan/vulkan_trace_viewer_main.cc
src/xenia/hid/hid_demo.cc
src/xenia/ui/vulkan/vulkan_window_demo.cc
src/xenia/vfs/vfs_dump.cc
tools/build/src/test_suite_main.cc

- Fix up handling of positional options in cvar handling so that executables other than app can handle them properly.
- Fix command-line arguments for xenia-vfs-dump.

Fix up handling of positional options in cvar handling.

---

src/xenia/base/memory.h

This is so the `std::string` and `std::wstring` variants pass the string in as a const ref instead of needlessly copying.

[Base] Make value argument for store and store_and_swap templates const&.

---

docs/building.md

Was the start project renamed from 'xenia' to 'xenia-app' in the past?

[Docs] Fix project name in building.md

---

premake5.lua

Fiber-safe optimizations actually worsen performance.

Remove /gt & OpenGL leftovers

---

src/xenia/debug/ui/debug_window.cc
src/xenia/gpu/trace_viewer.cc
src/xenia/ui/imgui_drawer.cc
src/xenia/ui/imgui_drawer.h
src/xenia/ui/window.cc
src/xenia/ui/window_demo.cc
third_party/imgui.lua

- Submodule is updated.
- All removed APIs are replaced.
- All APIs that have been deprecated are replaced.
- Biggest code changes are that ownership of the font atlas is now handled by imgui itself (xenia could do it as well but there is no benefit in that) and how the draw lists are processed (they are now processed once by the window class after all painting callbacks are returned because the old imgui callback mechanism is deprecated)
I tested this with the hid and ui demo, the profiler and guest debugger.
I didn't test trace viewers, please report if you find any regressions.

[imgui] Update to latest upstream master.

---

src/xenia/cpu/xex_module.cc
src/xenia/cpu/xex_module.h
src/xenia/kernel/user_module.cc
src/xenia/kernel/util/xex2_info.h

XEX1's are found in builds created before SDK 1888. Currently the only way to run them is by owning XeDK hardware (beta XDK), which aren't easy to come by. Though there still are more incompatibilities that need to be worked on, this allows them to be loaded and executed.
This fix is simple as the only difference appears to be in the security info structure (xex2_security_info). I just created a new structure named SecurityInfoContext which points to or loads all the info needed from the security info structure in the XEX header. 
Here are the changes made:
- Exception was made for the "XEX1" magic in `UserModule::LoadFromMemory()`.
- `xex1_security_info` structure was added to xex2_info.h
- `GetSecurityInfo()` now returns a void pointer which just points to either the XEX1 or XEX2 …

[Kernel] Enable XEX1 loading

---

src/xenia/ui/imgui_drawer.cc

By default imgui saves an INI file named `imgui.ini` to the current directory, which is undesired behavior.
Until we can properly specify a full path to a good location, disable saving of the INI file.

[UI] Disable saving of imgui INI file.

---

src/xenia/cpu/backend/x64/x64_emitter.cc
src/xenia/cpu/backend/x64/x64_emitter.h
src/xenia/cpu/backend/x64/x64_seq_vector.cc

- Fix corruption of src1 in non-AVX2 path.
- Fix constant src2 in AVX2 path (from @CookiePLMonster).

[x64] VECTOR_ROTATE_LEFT_V128 fixes

---

src/xenia/kernel/util/object_table.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_ob.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_threading.cc
src/xenia/kernel/xobject.cc
src/xenia/kernel/xthread.cc

This PR consists of three parts:
1) The first commit adds some useful assertions which I used to debug issues fixed in later commits.
2) Second commit stops `ExCreateThread` from retaining the handle. Despite the comment from 64b2be92d64361c437c6ba1de6f82296200be75b, I believe this handle should **not** be retained, as the thread is supposed to be freed once it finishes executing **and** it's handle is closed. Since every `XObject` contains a handle to itself on creation, retaining the handle further on creation would result in always having this one handle linger, and thus not freeing thread objects.
I have not extensively tested this but I've noticed threads started being properly deleted after intro videos in Forza Horizon 2. According to @Gliniak, numerous lingering threads in Lost …

[Kernel] Fixes to thread reference counters

---

src/xenia/base/clock.cc
src/xenia/base/clock.h
src/xenia/base/clock_posix.cc
src/xenia/base/clock_win.cc
src/xenia/base/clock_x64.cc
src/xenia/base/math.h
src/xenia/cpu/backend/x64/x64_sequences.cc
src/xenia/kernel/xthread.cc

There is a dedicated clock for each thread, updated independently. Upon thread save and restore these time values are preserved. 
I see no reason for this as time naturally progresses evenly for all threads (except the xbox360 is rotated very fast with one core as it's center and the power button near the speed of light which is hard to emulate anyways...). **This causes time to drift between different threads** and causes issues in many games that retrieve tick counts from more than one thread like RAGE engine titles (RDR, GTA). Additionally there is questionable **floating point arithmetic involved in translating the 64 bit tick count** between host and guest.
Both of these issues can cause guests to see time regress.
The **Clock state now is unique** and dynamic fields are protected by …

[Base] Fix Clock

---

src/xenia/kernel/kernel_state.cc
src/xenia/kernel/kernel_state.h
src/xenia/kernel/xboxkrnl/xboxkrnl_modules.cc

This PR consists of two fairly separate parts:
1) The first commit corrects a few places in XEX loader where modules were incorrectly reference counted. Most notably, `object_ref`, which refcounts objects automatically, was used alongside manual `Retain()` calls. This probably caused handle leaks - there might be more to go, but at least some of them are fixed now.
2) The second commit fixes implementation flaws in `XexUnloadImage`. Previously, releasing the last reference to a module performed only a partial cleanup. This resulted in issues such as:
- Attempting to notify an inexistant module when sending `DLL_THREAD_ATTACH` and `DLL_THREAD_DETACH` events. In my experience those were non-fatal but results may vary per game.
- Not loading a XEX module fully after a chain of `Load` -> …

[Kernel] Improve XexUnloadImage and module refcounts

---

src/xenia/ui/window.cc
src/xenia/ui/window.h

- Because frame time is calculated based on `GetSystemTimeAsFileTime()` a time delta of zero is possible (Value is 100ns resolution but apparently not updated at that rate by the system).
- A new imgui frame is created before it is verified the context isn't lost.

[UI] Fix misc imgui things.

---

src/xenia/kernel/xboxkrnl/xboxkrnl_memory.cc

Changes `NtAllocateVirtualMemory` so that it ignores specified page size when a base address is specified.
Fixes a crash seen in N3 demo boot.

[Kernel] Ignore page size with base address allocations.

---

src/xenia/app/emulator_window.cc
src/xenia/app/emulator_window.h
src/xenia/base/filesystem_win.cc
src/xenia/base/platform.h
src/xenia/base/string.cc
src/xenia/gpu/shader.cc
src/xenia/ui/ui_event.h
src/xenia/ui/window_win.cc

This PR lifts `MAX_PATH` limit from all code places which still used it. Most of current instances of it could be trivially removed either by calling functions twice (first to determine required buffer size, then to do actual work) or by replacing them with their memory-allocating counterparts.
The end result is a complete removal of `kMaxPath` constant on Windows. It's now unused and I think it's a good idea not to keep it to encourage not using any hardcoded constants for functions operating on paths.

Removal of MAX_PATH limit on Windows

---

src/xenia/cpu/backend/x64/x64_code_cache.h

Few games have function count higher than 50k.
Ghidra and IDA reports the same number of functions.
Confirmed titles: _Watch Dogs_, _Far Cry 3_
Benefits: It allows FC3 go a little bit further, but still crashes.
Screen from IDA (FC3): https://media.discordapp.net/attachments/440280035056943104/675094290426494984/unknown.png

[CPU] Increased maximum function count

---

src/xenia/hid/hid_demo.cc

Fixes #1490 
`Setup()` was not called on XInput driver.
This fix calls it on winkey driver as well to prevent future regressions.
(Although it is not needed right now but that should be up to the implementation to decide)

[HID] Fix Demo for XInput

---

src/xenia/app/xenia_main.cc

The current placement of the check of the cvars to start the discord RPC (at the beginning of xenia_main) doesn't actually check the toml.
This PR moves the check to after the toml is imported and the cvars are populated, allowing `discord = false` in the toml to actually disable discord RPC.

[App] Fix discord cvar

---

src/xenia/cpu/ppc/ppc_emit_alu.cc

These opcodes are barely used. I implemented them, by looking at different, but similar instructions and merged what I needed.
If required I might split this commit in two. (commit per instruction)
**Disclaimer:** I cannot provide tests for them as I cannot check them on console.
FYI: other opcodes from this "group" don't have tests
**Usage:**
Only known titles that uses them are _Telltale_ games to decompress data.
Impact:
It makes _Telltale Batman_ startable and probably also few other _Telltale_ titles
There is also Borat for your commitment
[Power ISA v3.0B](https://openpowerfoundation.org/?resource_lib=power-isa-version-3-0)

[CPU] Implemented instructions: rldclx, rldcrx

---

src/xenia/cpu/ppc/ppc_decode_data.h
src/xenia/cpu/ppc/ppc_emit_control.cc
src/xenia/cpu/ppc/ppc_instr.h
src/xenia/cpu/ppc/ppc_opcode_disasm_gen.cc
src/xenia/cpu/ppc/ppc_opcode_info.h
src/xenia/cpu/xex_module.cc
tools/ppc-instructions.xml
tools/ppc-table-gen

This adjusts Xenia's internal usage of the syscall instruction (`sc`) to use a reserved form, so that when some titles— Xbox 1 emulation, XNA, Internet Explorer, etc (notably all from Microsoft) that actually use the syscall instruction will be picked up properly instead of being mistaken for Xenia's usage of syscalls.
This will allow us to lay in the groundwork to eventually have proper syscall handling.

Syscall rework.

---

xenia-build

On some languages of Windows (mine is Japanese), python will expect the default text encoding to be the system encoding. This does not work when parsing the output of vswhere set to output in UTF-8 when the system encoding is not UTF-8.
Fixes #1479

[XB] Fix python not expecting UTF-8 for the output of vswhere

---

src/xenia/kernel/xboxkrnl/xboxkrnl_strings.cc

This PR fixes some issues with string formatting, which mainly effects the dashboard (preventing it from displaying any achievement icons), but I guess could maybe be ran into with some games too.
The first commit fixes the \*FormatData classes: previously the peek() method of these didn't return values in the same endian as get(), which would break code that tries reading from a wide-string using peek() (eg. format_core when it encounters %I), since the value read via peek() would be in the wrong endian.
I've just changed peek() so that it byte-swaps the return value if the get() method also byte-swapped it, and now format_core can read wide chars using peek() fine.
There was also an issue with the skip() method, where it didn't actually advance the input and would just keep checking the …

[Kernel] format_core string formatting fixes

---

src/xenia/kernel/xam/xam_net.cc

This is based on description from [this site](https://www.intervalzero.com/library/RTX/WebHelp/Content/PROJECTS/SDK%20Reference/WinsockRef/WSAFDIsSet.htm) as Microsoft don't provide information about return value.
~~I marked it as _Sketchy_. Documentation says that it returns integer when socket was found in _fd_set_, but it does not specifies what value (is it 1 or provided socket).~~
Update: Thanks RedMadKnight for providing info about returned value
_Renegade Ops_ goes ingame
_Test Drive Unlimited 2_ might go further

[XAM/Network] Implemented NetDll___WSAFDIsSet

---

src/xenia/kernel/xam/xam_notify.cc

Based on dissasembled **_Ghost Recon AW2 Demo_**
I attached fragment from IDA to have confirmation that such situation might occur.
IDA proof:

[Kernel/XAM] XNotifyGetNext: Check for nullptr for param_ptr

---

docs/building.md
tools/build/premake
xenia-build

- `xb devenv` command on Linux to generate CodeLite workspace and start it.
- Replace premake with upstream master revision, needed to fix CodeLite related bug. (Only change to our fork is making premake build on PowerPC - do we still need this?)
- Update building documentation.
With these changes getting an IDE and starting debugging is as easy as it is on Windows (At least on current *ubuntus). CodeLite may be inferior to CLion or others but automatic project file generation is key here.

Make starting development on Linux easier.

---

src/xenia/app/emulator_window.cc
src/xenia/app/xenia_main.cc
src/xenia/base/filesystem.cc
src/xenia/base/filesystem.h
src/xenia/base/filesystem_posix.cc
src/xenia/base/filesystem_win.cc
src/xenia/base/main_win.cc
src/xenia/config.cc
src/xenia/gpu/d3d12/pipeline_cache.cc
src/xenia/gpu/shader.cc
src/xenia/gpu/trace_writer.cc
src/xenia/gpu/trace_writer.h
src/xenia/hid/sdl/sdl_input_driver.cc
src/xenia/kernel/xam/content_manager.cc
src/xenia/kernel/xam/user_profile.cc
src/xenia/kernel/xfile.h
src/xenia/ui/imgui_drawer.cc
src/xenia/vfs/devices/disc_image_entry.h
src/xenia/vfs/devices/host_path_device.cc
src/xenia/vfs/devices/host_path_entry.cc
src/xenia/vfs/devices/stfs_container_device.cc
src/xenia/vfs/devices/stfs_container_entry.h
src/xenia/vfs/vfs_dump.cc
src/xenia/vfs/virtual_file_system.cc

With C++17 filesystem implemented, some of the `xe::filesystem` functions have become obsolete platform implementations of what the standard library already provides.
This PR removes `xe::filesystem::IsFolder`,  `xe::filesystem::PathExists`,  `xe::filesystem::CreateFolder`,  `xe::filesystem::DeleteFolder` and  `xe::filesystem::DeleteFile` and replaces them with their `std::filesystem` counterparts in the place where they are called.
This has the added bonus of implementing those functionalities in Posix as well.

Use std::filesystem for simple queries and operations

---

src/xenia/emulator.cc

- [Core] Fix guest crash handler crash due to bad format string.
- [Core] Fix guest crash handler outputting signed values for vectors.

[Core] Fix guest crash handler crash/output.

---

src/xenia/base/filesystem_win.cc
src/xenia/cpu/elf_module.cc
src/xenia/emulator.cc
src/xenia/gpu/command_processor.cc
src/xenia/gpu/d3d12/d3d12_command_processor.cc
src/xenia/gpu/d3d12/render_target_cache.cc
src/xenia/gpu/d3d12/texture_cache.cc
src/xenia/gpu/vulkan/render_cache.cc
src/xenia/gpu/vulkan/texture_cache.cc
src/xenia/gpu/vulkan/vulkan_command_processor.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_debug.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_video.cc
src/xenia/ui/vk/transient_objects.cc
src/xenia/ui/window_win.cc
src/xenia/vfs/devices/stfs_container_device.cc

Avoid using '#' format spec for X (uppercase) hex numbers, as it results in output like "0XABCDEF" instead of "0xABCDEF".

Avoid using '#' format spec for X hex numbers.

---

src/xenia/cpu/export_resolver.cc
src/xenia/cpu/xex_module.cc
src/xenia/kernel/kernel_module.cc

A minor fix eyeballed while discussing related functionality. Fixes two tiny issues in `KernelModule::GetProcAddressByOrdinal`:
1. Now properly takes a global lock. Previously return value from `global_critical_region_.Acquire()` was discarded, which effectively locked and immediately unlocked the global lock.
2. Cases where a trampoline for ordinal was already created called `guest_trampoline_map_.find(ordinal)` twice for no reason. Now it's only called once - potentially a micro-optimization.
Chance of affecting games in any measurable way is near zero, unless there is a game which furiously calls `XexGetProcedureAddress` on the same module **concurrently** - in which case this pre-emptively prevents a race condition on populating the guest trampolines map.

[Kernel] Fixup GetProcAddressByOrdinal

---

src/xenia/kernel/xam/apps/unknown_fe_app.cc

Sometimes games uses not defined xam exports as a 0xFE app with different msgid.
Usually lack of even dummy support for such action causes game to return I/O Error or crash.
0x21012:
- _FUSE_
0x22005: most EGO engine games
- _Grid 2_
- _Grid Autosport_
- _Toybox Turbos_

Added new 0xFE app message

---

src/xenia/kernel/xam/user_profile.cc

[XAM] Modify default user XUID. Fixes behavior in NeoGeo Battle Coliseum and possibly others. ("You do not have permissions to perform this operation.")

[XAM] Modify default user XUID.

---

src/xenia/base/utf8.cc
src/xenia/base/utf8.h
src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc
src/xenia/kernel/xfile.cc
src/xenia/vfs/devices/disc_image_device.cc
src/xenia/vfs/devices/host_path_device.cc
src/xenia/vfs/devices/stfs_container_device.cc
src/xenia/vfs/entry.cc
src/xenia/vfs/entry.h
src/xenia/vfs/virtual_file_system.cc
src/xenia/vfs/virtual_file_system.h

[Base] Fix canonicalize path for rooted paths.
[Base] Join paths better, so the first iteration isn't a join of an empty string with the first path part.
[Base] Add optional argument to allow empty parts in `utf8::split`.
[Base] Make utf8 arguments consistent. Fix `sep` to `separator`.
[VFS] Allow specifying root entry to open from with `OpenFile`.
[Kernel] `NtCreateFile` now opens from root entry when available instead of needlessly building a full path and resolving from that.
[VFS] Reduce code duplication by adding `Entry::ResolvePath`.
[VFS] Remove `ResolveBasePath` to avoid multiple calls to `find_base_guest_path`.

Rooted path fixes.

---

src/xenia/kernel/xam/xam_net.cc

Fixes Peggle 2 (xenia-project/game-compatibility#734) startup crash.

[XAM] Dummy MAC address in *XNetGetTitleXnAddr.

---

src/xenia/kernel/xam/xam_content.cc

Few games for some reason use XamContentCreateInternal for creating savefiles
XamContentCreateInternal vs XamContentCreateEx comparation:
(To see differences in function arguments)
``XamContentCreateInternal`` code:
```mr        r10, r26      # int
stw       r24, 0xB0+var_54(r1) # int
mr        r9, r27       # int
std       r25, 0xB0+var_60(r1) # __int64
mr        r8, r28       # int
mr        r7, r29       # int
li        r6, 0x200     # int
mr        r5, r31       # int
mr        r4, r30       # int
li        r3, 0xFE      # int
bl        sub_818BFBD8 
```
``XamContentCreateEx `` Code:
```lwz       r11, 0xB0+arg_54(r1)
mr        r10, r25      # int
mr        r9, r26       # int
std       r24, 0xB0+var_60(r1) # __int64
mr        r8, r27       # int
mr        r7, r28       # int
li …
```

[Kernel/XAM] Implemented XamContentCreateInternal

---

src/xenia/gpu/command_processor.cc
src/xenia/gpu/gpu_flags.cc
src/xenia/gpu/gpu_flags.h
src/xenia/gpu/xenos.h

Writes some fake data in response to occlusion queries.
cvar `query_occlusion_fake_sample_count` was added which determines the sample count that is reported as passed. This is set to 1000 at default since games which use occlusion culling become basically useless with 0 (everything occluded).
This should affect many games but most importantly allows Unreal Engine games to run since they block infinitely on query results.

[GPU] Add workaround for occlusion queries.

---

src/xenia/kernel/xam/xam_content.cc
src/xenia/kernel/xam/xam_ui.cc

Correct storage device ID fixes saving and storage detection in many games
most of the games this can be evidenced in are Unreal Engine titles or games that otherwise do not work in master yet but it can be shown in Saints Row 2 that does work in the master branch
this ID was found from debugging games where storage device detection wasn't working and reverse engineering of Unreal Engine 3

[XAM] Correct storage device ID fixes saving and storage detection

---

src/xenia/kernel/xboxkrnl/xboxkrnl_threading.cc

Based on description on this site: [link](http://undocumented.ntinternals.net/index.html?page=UserMode%2FUndocumented%20Functions%2FAPC%2FNtQueueApcThread.html)
> Function adds user defined routine to thread's APC queue. This routine will be executed when thread will be signaled.
I've found that we have function that does exactly "that" which is called: `EnqueueApc`.
I also added some stuff to log, but we might talk about if it is really required here.
I tested it on SW:TFU and instead of stucking on loading it goes ingame and work quite nicely.

[Kernel] Implemented NtQueueApcThread

---

src/xenia/ui/imgui_drawer.cc

Every context after the first wasn't initialized properly.
So things like special keys (e.g. enter) where not working in any other window than the main window.

[ImGui] Fix context initialization.

---

src/xenia/base/logging.h

We can't undefine `XELOGDUMMY` like this, so instead "hide" it by prefixing it with underscores.

Fix building with XE_OPTION_ENABLE_LOGGING off

---

src/xenia/kernel/xam/xam_content.cc

Simple addition based on Fifa Street Demo behaviour.
Now some EA games should have working savefiles

[Kernel/XAM] Added Support For: XamContentDeleteInternal

---

src/xenia/kernel/xboxkrnl/xboxkrnl_memory.cc
src/xenia/xbox.h

TL;DR
Some games care about returning X_MEM_FREE state.
I also changed flags/masks to be enum instead of define

[Kernel/Memory] NtQueryVirtualMemory - Added support for returning X_MEM_FREE state

---

src/xenia/kernel/util/object_table.cc
src/xenia/kernel/util/object_table.h
src/xenia/kernel/xobject.h

In first versions of Burnout Paradise there is code that rely on correct handle value.
uVar1 is handle to the thread that is stored via Tls.
If you calculate with actual values it looks like we're off to incorrect memory space (around 0x8A, but we should be at 0x82...)
Affected Titles:
- Burnout Paradise v1.0 (including demo)

[Kernel/Object] Added base to object handle

---

src/xenia/kernel/xboxkrnl/xboxkrnl_usbcam.cc

- Provided description to some parameters
- Provided description what function more/less should do
- Changed return code based on game behaviour
Comment:
Based on fragment of game code:
I tested few values, but only 0 seems to be reasonable.

[Kernel/Usbcam] XUsbcamCreate

---

src/xenia/kernel/xboxkrnl/xboxkrnl_threading.cc
src/xenia/kernel/xthread.cc
src/xenia/kernel/xthread.h

I found out that ``KeSetAffinityThread`` have optional parameter. I called it ``affinity_ptr``, but feel free to provide better name 
Here we can see few things.
1. Param2 must be lower than 6 (cpu_core?)
2. KeSetAffinityThread have 3 parameters (3rd is a pointer)
3. Output of that function depends on value under 3rd parameter.
These 2 fragments are usages of that function above. We can see that second argument is check on input and output and that parameter is used as affinity (to be precise: 1 << param2)

[Kernel/Thread] Added missing paramteter to KeSetAffinityThread

---

src/xenia/base/debugging_posix.cc

Check `TracerPid` in `/proc/self/status` for attached debugger.
Add `SIGTRAP` handler to prevent signal from halting app while not running
in a debugger.
Log `DebugPrint` in `clog` (`stderr`).

Implement debug functions for Linux

---

.gdbinit
src/xenia/app/emulator_window.cc
src/xenia/apu/xma_decoder.cc
src/xenia/base/logging.cc
src/xenia/base/testing/threading_test.cc
src/xenia/base/threading.h
src/xenia/base/threading_posix.cc
src/xenia/base/threading_win.cc
src/xenia/gpu/command_processor.cc
src/xenia/gpu/graphics_system.cc
src/xenia/kernel/kernel_state.cc

Current Status on master
---
On Linux, the Xenia app and many of the test ui tests do not run correctly due to waits on `WaitHandles` flowing through and returning early.
Fix status of this PR
---
I have been working on this PR for about a year and it now has reached a point where I consider it done and ready for review.
This PR implements most of `threading_posix.cc` by TDD to make sure behaviour is the same as win32.
This is a follow-up to (#1108) in order to get xenia to actually run on Linux. Following this, a few GTK-Vulkan fixes need to be done as well as implementing POSIX file system stubs. With those, a GTK window actually appears and responds to events.
Fix description
---
Borrowed commit from #1076 for Linux debug symbols.
Fixed occurrences of micro/millisecond confusion on …

Threading unit tests and linux threading implementation

---

src/xenia/base/string_util.h
src/xenia/kernel/xam/xam_content.cc
src/xenia/kernel/xam/xam_info.cc
src/xenia/kernel/xam/xam_ui.cc
src/xenia/kernel/xam/xam_user.cc

This supersedes and more correctly includes #1632. Ensures null termination of strings written by certain kernel functions even in case of buffer overflow. I'm not sure about the designed overflow behavior of the kernel functions when I'm using the new copying, but overall this seems safe, also fixes the issue found by @Gliniak in #1632.

[Base/Kernel] Add and use truncating null-terminating string copying

---

src/xenia/apu/xma_context.cc

It seems like setting output buffer to invalid when there is no valid input buffers resolves annoying bug, when games freezes if sound gets corrupted.
Now instead of freezing, games can correctly playback sounds or skips for like 125ms or less.

[APU/XMA] Invalidate output buffer when there is no valid input buffer

---

src/xenia/kernel/xam/xam_content.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_module.cc

These couple of fixes fix up all the rest of the storage detection issues I can find with the caveat of XamUIDeviceSelector needing some solution to set its pointer after a delay
The kernel commit sets the same flag to XboxHardwareInfo that the kernel does at startup after storage is initialized, found disassembling the kernel trying to debug why these last few problems with storage being detected persisted.
The commit to xam_content changes the size of the storage being reported as a hdd device type to the smallest size hdd that shipped with the 360, this fixed saving in Rapala fishing.
The changes to byteswap the deviceinfo struct in XamContentGetDeviceState fix a large number of storage detection issues in many games, with the caveat that a solution is needed in Xam_UI to …

Xam content / Storage fixes

---

src/xenia/base/testing/threading_test.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_module.cc

The high performance test atomic counters need to be set to zero to have reliable results.

threading test: zero initialize counter

---

src/xenia/kernel/xam/user_profile.h
src/xenia/kernel/xam/xam_user.cc

- [XAM] Fix `XamUserGetXUID` type mask handling.
- [XAM] Fix `XamGetUserName` return values.
- [XAM] Fix `XamGetUserName` copy size.
- [XAM] Implement `XamGetUserGamerTag`.
- [XAM] Fix `XamUserCheckPrivilege` handling of all users.
- [XAM] Stub `XamUserGetMembershipTier`.

[XAM] Rollup of user fixes.

---

src/xenia/base/testing/threading_test.cc
src/xenia/base/threading_posix.cc

Fix a failed test because of too small stack in pthreads attr. This in not the theoretical minimum on the platform, but the actual needed `PosixThread` size.
Fix an on exit assert fail.

Threading test fixes

---

src/xenia/base/memory.h
src/xenia/base/memory_posix.cc
src/xenia/base/memory_win.cc
src/xenia/base/testing/memory_test.cc
src/xenia/cpu/backend/x64/x64_code_cache.cc
src/xenia/kernel/util/shim_utils.h
src/xenia/memory.cc

Here are various memory implementation Fixes for Xenia to run on Linux.
As of this draft, they go as far as getting something on screen, but they do go farther in the initialization.
* Cherry picked some improvements from @uytvbn from another unmerged PR
* Moved some Windows specific code about Virtual File Mappings to the win implementation and added Linux/Posix specific code to the posix implementation
* Fixed a leak of shared memory handles on Linux
* Added a few tests
* Fixed a subtle compiler issue in kernel which was causing guest-to-host args to compile out of order on clang. 
<details><summary>Small example</summary>
<p>
The following code does the same thing as `RegisterExport` in `src/xenia/kernel/util/shim_utils.h` but clearly shows the issue with compiler inconsistency of …

Linux memory Fixes

---

.gitmodules
src/xenia/kernel/xboxkrnl/xboxkrnl_rtl.cc
src/xenia/kernel/xclock.h

- Add `date` third party submodule.
- [Kernel] Add `xclock`.
- [Kernel] Reimplement `RtlTimeToTimeFields` using `std::chrono`/`date`/`xclock`.
- [Kernel] Reimplement `RtlTimeFieldsToTime` using `std::chrono`/`date`/`xclock`.
- Supersedes #1612.

[Kernel] Overhaul Rtl time functions.

---

src/xenia/kernel/xboxkrnl/xboxkrnl_debug.cc

Thread names from the guest code can be any random encoding (usually developer specific) such as SJIS, which is not valid UTF-8. This will throw exceptions if it's attempted to be converted to UTF-16 in our internal thread name setting code.

[Kernel] Filter thread names from guest.

---

src/xenia/kernel/xboxkrnl/xboxkrnl_memory.cc

I found out that Black Ops 3 explicitly calls ``MmSetAddressProtect`` with protect bits 0. Which seems to be unhandled case by us.
Right now providing 0 causes it to mark it as PAGE_NOACCESS, which seems to be incorrect as PAGE_NOACCESS is 0x01
Providing 0 do not cause any change to provided range and old protection stays intact.
```
d> F8000028 MmSetAddressProtect(BF8A0000, 00400000, 00000000)
d> F8000028 ! EMULATOR PAUSED !
!> F8000028 ==== CRASH DUMP ====
```
You can see r5 is set to 0
Now there is only one operation on it which might be translated to: r23 = r5 & 0x7fffffff
We're skipping some code that doesn't impact r23 and go to place where ``MmSetAddressProtect`` is called

[Kernel/Memory] MmQueryAddressProtect - Check for protect_bits equals 0

---

src/xenia/kernel/xboxkrnl/xboxkrnl_memory.cc
src/xenia/kernel/xfile.cc
src/xenia/memory.cc
src/xenia/memory.h

TL;DR
NtAllocateVirtualMemory, NtFreeVirtualMemory and NtProtectVirtualMemory shouldn't be able to allocate memory over physical or xex range.
I'm making it as draft for future updates (switch from hardcoded value into some const etc)
<This PR is for testing purposes right now.>
Affected titles (positive):
- Stormrise
- London 2012
- Dead or Alive 4
Affected titles (negative):
-TBD

[Kernel/Memory] Restrict Nt<whatever>VirtualMemory only to virtual memory range

---

tools/build/scripts/test_suite.lua
tools/build/src/test_suite_main.cc

Use xenia-base entrypoint for test suites. Fixes a bug where we were expecting `wchar` data in `main`, which is incorrect, causing invalid args to be parsed.

Use xenia-base entrypoint for test suites.

---

src/xenia/base/mutex.h
src/xenia/kernel/kernel_state.cc
src/xenia/kernel/kernel_state.h
src/xenia/kernel/xam/xam_notify.cc
src/xenia/kernel/xam/xam_ui.cc
src/xenia/kernel/xnotifylistener.cc
src/xenia/kernel/xnotifylistener.h

- [Kernel] Fix global locking in kernel dispatch thread.
- [Kernel] Improve `CompleteOverlappedDeferred`/`CompleteOverlappedDeferredEx`.
- [XAM] Identify unknowns in `XamNotifyCreateListener`/`XNotifyListener`.
- [XAM] Defer `XamShowMessageBoxUI`.
- [XAM] Defer `XamShowKeyboardUI`.
- [XAM] Fix cancel handling in `XamShowKeyboardUI`.
- [XAM] Defer `XamShowDeviceSelectorUI`.
- [XAM] Defer `XamShowDirtyDiscErrorUI`.

Defer XAM UI functions & other improvements.

---

src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc
src/xenia/kernel/xfile.cc
src/xenia/vfs/virtual_file_system.cc
src/xenia/vfs/virtual_file_system.h
src/xenia/xbox.h

Different title suggestions will be appreciated 👍 
I found out that fifa 07 tries to do this:
```
d> 00000028 NtOpenFile(7018F590(00000000), 00100001, 7018F5B0(FFFFFFFD,D:\,00000040), 7018F5A8, 00000003)
.
.
.
d> 00000088 RtlInitAnsiString(701EF8E8, 701EF990(D:\))
d> 00000088 NtCreateFile(701EF8E0(FFFFFFFF), 80100080, 701EF8F8(FFFFFFFD,D:\,00000040), 701EF8F0, 00000000, 00000080, 00000001, 00000001, 00000060)
```
For the first case it's fine it should return 0, but for second not so fast. 
It receives only D:\ (checked also during debugging) as a target_path without any file name with flag 0x40 (FILE_NON_DIRECTORY_FILE)
In such case we should return X_STATUS_FILE_IS_A_DIRECTORY instead of 0.

[Kernel/IO] Return error when creating directory with non-directory flag in NtCreateFile

---

src/xenia/ui/window_gtk.cc

If one were to set a kPopup as a child of a kPopup (as ObsidianNA does in #1396), GTK will assert that the parent kPopup is not a submenu and refuse to set the child.
This changes the current behaviour by creating an intermediary submenu when one sets a kPopup as a child of a kPopup so that the menuing works as intended.

[GTK UI] Fix GTK submenus

---

src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc
src/xenia/kernel/xiocompletion.cc

Additionally: "Fixed" issue where executing WaitForNotification with wait_ticks 0 caused it to return timeout.
I'm still leaving that change to debate, as it seems to be hacky-like fixed (that is why I quoted it).
It seems like it is timing issue between ``NtSetIoCompletion`` and ``NtRemoveIoCompletion`` if they're executed too close to each other sometimes it might return timeout even if it shouldn't
- [Naughty Bear: Gold Edition](https://github.com/xenia-project/game-compatibility/issues/680)
- [Wet](https://github.com/xenia-project/game-compatibility/issues/671)

[Kernel] Implemented NtSetIoCompletion

---

src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc
src/xenia/kernel/xfile.cc
src/xenia/kernel/xfile.h

This implements the NtReadFileScatter kernel export, the export code is pretty much identical to NtReadFile besides the buffer parameter being a pointer to an array of buffer pointers (seems these are meant to be of union FILE_SEGMENT_ELEMENT, but they can be treated as uint32 fine)
This buffers parameter is passed along to a newly added XFile::ReadScatter, which handles looping over the remaining bytes to read and using XFile::Read to read into each buffer in turn.
(AFAIK the buffers are each 4096 bytes, most info on the net about NtReadFileScatter says that the buffers are memory-page-sized, not sure if that means the buffer size could change depending on page-size of the buffers memory area though - the only game I've seen using this always seems to use 4096 bytes for each buffer)
In …

[Kernel] Implement NtReadFileScatter

---

src/xenia/cpu/xex_module.cc
src/xenia/cpu/xex_module.h

- Move security info conversion code into ReadSecurityInfo
- Update ApplyPatch to call ReadSecurityInfo after patching headers
Right now ApplyPatch doesn't update security_info_ after applying a patch, making image_size() & other code that relies on security_info_ return outdated/incorrect data.
This can be seen when applying the Saints Row title update, before applying patch image_size() returns a normal 0x02160000, but after patching it returns 0x6d060000, which ends up breaking the memory alloc code inside ApplyPatch.
Changing ApplyPatch to update security info after patching it returns a more normal 0x02040000 image size instead (and can be seen that security_info_.page_descriptor_count is lower after the patch, so I'm guessing the incorrect image size was likely due to the …

[CPU/XEX] Fix ApplyPatch not updating security_info_, causing issues with some patches

---

premake5.lua
src/xenia/base/fuzzy.cc
src/xenia/kernel/xclock.h
third_party/glslang-spirv/Include/PoolAlloc.h

The four commits are as follows
- Two are build fix for Linux on recent installations (I tested with clang-11 and libstdc++10) these should help #1735. The only issues left are with libav for me.
- One is a small cleanup to remove linking to unused libraries on Linux
- The last one is a missing header when using VS2017

Some small build fixes and changes

---

src/xenia/kernel/xam/xam_net.cc
src/xenia/kernel/xbdm/xbdm_misc.cc

- Change **DmRegisterCommandProcessorEx** & **DmWalkLoadedModules** result codes
- Make **NetDll_XNetQosServiceLookup** set the pqos output parameter to a valid pointer before returning
- Implement **NetDll_XNetQosRelease** to allow freeing the qos struct allocated by XNetQosServiceLookup
Previously Halo 3 debug would freeze if **DmRegisterCommandProcessorEx** didn't return success, and would get stuck in an endless loop if **DmWalkLoadedModules** didn't return 0x82DA0104, so I've updated both to return what the game seemed to expect.
(wasn't sure about PRing these since there might have been a reason they had the result codes they did, but I couldn't find any mentions on the compatibility tracker for either export after a quick search, so hopefully this shouldn't break anything) …

[Kernel] Improved export stubs, implement XNetQosRelease

---

src/xenia/kernel/xam/xam_content.cc

Based on disassembly of Silent Hill: Homecoming
I figured out that it checks for very specific extended error codes. 
On screenshot you can see two of them: 
0x80070003 - X_ERROR_PATH_NOT_FOUND
0x80070570
and there is also one more check for:
0x80070026
We're not returning the first one (correct path) or any other error code and games goes a little insane and runs second instance of main menu in the background which causes issues.
- Silent Hill: Homecoming - It fixes issue when pressing Start Game/Load Game causes window to pop and then returns to main menu & saving
- Ridge Racer 6 - Fixes saving
- Ridge Racer Unbounded - Fixes initial save (second save still crashes due to used handle to savefile)
- Wartech: Senko no Ronde - Resolves no device found error (before main menu) & saving …

[Kernel/XAM] XamContentCreateEx - Extended Error Support

---

src/xenia/kernel/xboxkrnl/xboxkrnl_memory.cc

Based on research on console and document provided by @Triang3l (Thanks 🦊 )
Link to document: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntallocatevirtualmemory
Last sentence from RegionSize description says: 
> RegionSize cannot be zero on input.
Right now we don't care when game provides 0 as region_size_ptr what causes it to be sucessful and allocate 2 pages (iirc)
Meanwhile this action should fail with code: ``X_STATUS_INVALID_PARAMETER``
- NBA Live games

[Kernel/Memory] Return error when region_size is 0

---

src/xenia/kernel/xam/xam_content.cc

Based on ``Bodycount`` game I figured out that in ``XamContentCreateEx`` we're not returning ``disposition`` when we're using ``overlap``.
I simply removed code responsible for clearing it out. We're using ``CompleteOverlappedImmediateEx`` to handle overlap, so it is instant anyway.
Fragment of code just in case 🐑 
- Bodycount

[XAM/Content] Set disposition for overlapped cases

---

src/xenia/kernel/xboxkrnl/xboxkrnl_crypt.cc

It was quite trivial to implement so no description here. 🐑 
- Forza Motorsport 3 - Now doesn't return tampered error

[Kernel] Implemented: XeKeysHmacShaUsingKey

---

src/xenia/base/testing/utf8_test.cc
src/xenia/base/utf8.cc
src/xenia/base/utf8.h

[Base] Fix edge case in UTF-8 `find_name_from_path`/`find_base_path` with strings that consist of only a separator.
[Base] Dedupe new/old separators in UTF-8 `fix_path_separators`.
[Base] Plain string variant of UTF-8 `join_paths`.
Add macro for automatically testing both `/` and `\` of all path input/outputs.
Add more UTF-8 path edge cases.

UTF-8 edge cases.

---

src/xenia/kernel/xam/content_manager.cc
src/xenia/kernel/xam/content_manager.h

Based on ``Top Spin 4`` behaviour.
Seems like game tries to delete package without closing it. Which causes issue as game tries to open files within that package later and cannot find files.
I tried to poke with it on console with edited .xex and found out that ``XamContentDelete`` in this case it is not executed sucessfully and save stay where it was.
**Actual Behavior:** 
Open Package->Delete->Open File Fail
**New Behaviour:**
Open Package->Delete Fail->Open File Sucessful

[XAM/Content] Prevent deletion of open packages

---

src/xenia/emulator.cc
src/xenia/kernel/util/xdbf_utils.cc
src/xenia/kernel/util/xdbf_utils.h
src/xenia/kernel/xam/xam_info.cc
src/xenia/vfs/devices/stfs_container_device.cc
src/xenia/vfs/devices/stfs_container_device.h
src/xenia/xbox.h

This brings some improvements to the STFS structures and fixes some STFS handling issues, mostly related to CON profile/gamesave packages:
- STFS structures have been reorganized & improved to use `xe::be<T>`/bitfields/accessors, and remove the need for `read()` functions.
- `BlockToOffsetSTFS` has been fixed to work with CON/non-read-only-flagged packages.
- `GetBlockHash` now checks whether each levels secondary hash-block should be used or not in packages that have them, and updated the algo used for finding hash block for a given data block.
- `XdbfLocale` moved to xbox.h as `XLanguage`, so that `XContentMetadata` accessors can make use of it.
The structure improvements are pretty minor, existing structs already mapped out the headers pretty well, just reorganized them a little and …

[VFS/STFS] STFS structure improvements & CON support

---

src/xenia/kernel/xam/apps/xam_app.cc
src/xenia/kernel/xam/xam_enum.cc
src/xenia/kernel/xam/xam_user.cc
src/xenia/kernel/xenumerator.cc
src/xenia/kernel/xenumerator.h

This is mostly based on old canary achievement support.
I simplified it as much as possible to only provide basic implementation, which shouldn't crash titles.
- PGR4 - Fixes menu crash
- South Park XBLA - Fixes info popup about device being full (requires protect_zero)
- Some more?

[Kernel/XAM] Dummy X_ACHIEVEMENT_DETAILS support

---

src/xenia/kernel/xam/xam_enum.cc
src/xenia/kernel/xam/xam_user.cc

[XAM] Fix missing buffer check on `XamEnumerate`.
[XAM] Fix infinite loop in adding dummy achievement details when `count`>255.
[XAM] Cap the number of dummy achievement details.

[XAM] Achievement fixes.

---

src/xenia/kernel/xam/xam_user.cc

[XAM] Fix dummy achievement details count.
[XAM] Cap dummy achievement details to 100.
[XAM] Better text for dummy achievement details.
[XAM] Base dummy achievement details at ID 1.
[XAM] Provide image ID and flags for dummy achievement details.
[XAM] Define unknown args for `XamReadTileToTexture`.
[XAM] Write stub texture buffer (white) in `XamReadTileToTexture`.

More achievement fixes

---

src/xenia/kernel/xam/apps/xam_app.cc
src/xenia/kernel/xam/xam_content_aggregate.cc

1. WriteItems returns not masked error codes which in case for example of 0x12 (NO_MORE_FILES) will be treated as success.
2. Instead of returning hardcoded 1 as title_id for content_aggregate_data let's use already loaded title_id. 
- Dead Rising 2 (correctly loads savefiles)
- EA sports series
- Something more?

[XAM/Content] Improvements to aggregated content

---

xenia-build

It has been possible for some time now to install the VS Build tools for C++ without installing the VS IDE. However, the current xenia build script doesn't support this because vswhere only searches for an installation of the VS IDE by default. This is easily fixable by adding `-products Microsoft.VisualStudio.Product.BuildTools` to the vswhere command and would work whether the VS IDE is installed or not.

[Build] Support building with the standalone VS Build Tools

---

src/xenia/kernel/xam/content_manager.cc
src/xenia/kernel/xam/content_manager.h

I found that few games doesn't close explicitly handles to savefiles. They do not use ``NtClose`` to close these files (even on console)
However they use ``XamContentClose`` and seems like this function should be also responsible for closing opened files within content.
< space for more info >
If you know how to simplify this even more feel free to tell me 🐑 
- Ridge Racer Unbounded
- MindJack
- Spyro
- Saint's Row

[Kernel/XAM] CloseContent: Close files related to closed content

---

src/xenia/kernel/xam/xam_net.cc

Research based on: 
- https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-inet_addr#return-value
- Console
It seems like actual implementation of ``NetDll_inet_addr`` is slightly too new and doesn't exactly describes console behaviour
Old behaviour says that when you provide empty string it returns 0 (INADDR_ANY) instead of -1 (INADDR_NONE)
Note: Special case of providing only space in addr_ptr is handled correctly

[XAM/Net] inet_addr: Handle edge cases

---

src/xenia/apu/xma_context.cc
src/xenia/apu/xma_context.h

Previously about 0.5 to 1 ms was spend converting frames from ffmpeg format (le float) to dsp format (be int16).
With this patch, conversion time is negligible.

[APU] Add vectorized audio frame conversion

---

src/xenia/cpu/xex_module.cc

With Minecraft TU6 the previous code would allocate a buffer for the header which is too small, then when header delta-patch is applied it'd eventually overrun the header buffer and overwrite some other data, usually causing a crash (but not always)
The `size_of_target_headers` field seems to contain the correct size, but just in case it's not set somehow I also let it fall-back to the previous behaviour.
With this fix XEXP-patching should hopefully be pretty stable, at least Minecraft TU6-TU74 apparently don't have any issues after patching.
- Minecraft: TU6 XEXP now applies fine, previously would crash soon after patch was applied.

[CPU/XEX] Use correct size for XEXP-patched header buffer

---

src/xenia/apu/conversion.h
src/xenia/apu/sdl/sdl_audio_driver.cc
src/xenia/apu/sdl/sdl_audio_driver.h
src/xenia/apu/xaudio2/xaudio2_audio_driver.cc

- Vectorized copy/convert from guest to system audio back end
- SDL: Automatically down-convert to stereo if needed
- SDL: move conversion into callback function as it is no slower than generic memcpy
vector implementations are basically what clang 11 will auto optimize the cpp versions to (but as guarantee)
since msvc is very bad at auto vectorization we shall still add these
Windows MSVC:
Windows clang-cl:
clang-cl seems to use movbe instructions for optimizing instead of vectorization. (contrary to linux https://quick-bench.com/) We can't replicate that easily however because there are no intrinsics for that.

APU back end vector copy and conversion

---

src/xenia/base/clock_posix.cc

It's best to have this when working with #1431 because broken clock freaks ImGUI out and freezes hid demo
@bwrsandman put another version of this in #1433 originally but It's being held up by the other changes

[Base] Fix Clock platform functions on POSIX.

---

src/xenia/base/testing/utf8_test.cc
src/xenia/base/utf8.cc

Right now path like: ``game:\media\data360\\`` returns incorrectly file_name as empty string and base path as ``game:\media\data360``. In this case we should receive: ``data360`` as filename and ``game:\media\`` as base path.
Another way of dealing with it is by usage of ``fix_guest_path_separators``, but we would need to apply it to every path we're receiving, so this way is more universal 🤔

[Base] Remove multiple trailing separators in path

---

src/xenia/kernel/xboxkrnl/xboxkrnl_threading.cc
src/xenia/kernel/xthread.cc
src/xenia/kernel/xthread.h

Right now **KeEnterCriticalRegion** & **KeLeaveCriticalRegion** act on a global `xe::global_critical_region` shared between all threads, but AFAIK this seems to be wrong behaviour, most things I can find about NT's KeEnter/LeaveCriticalRegion say that those funcs should only be affecting APCs being ran on the caller thread and not all APCs globally, #1748 goes into this in more detail.
(that issue also talks about a problem this caused when trying to add threading to XamTaskSchedule, in a nutshell game code would run KeEnterCriticalRegion -> XamTaskSchedule -> WaitForSingleObject -> KeLeaveCriticalRegion, but as the critical region funcs affect all threads it'd stop XamTaskSchedule from being able to create/signal any other threads, only allowing code to run on the caller thread)
I've …

[Kernel] Make KeEnter/LeaveCriticalRegion only affect the caller thread

---

src/xenia/base/testing/utf8_test.cc

Im not sure if test case: `TEST_PATH(utf8::find_name_from_path, "/C/", "/C");` is even valid, but I can remove it at anytime.

[Base] Fixed edgecase in fnfp related to single char dirs

---

src/xenia/kernel/xam/xam_user.cc

This fixes an issue with loading profiles when selecting certain game modes (even if playing alone).
Specifically in Perfect Dark XBLA when you would try to load up the Combat Simulator, Co-operative, or Counter-operative game modes the title would display a loading message, and then just boot the user back to the main menu. 
https://github.com/xenia-project/game-compatibility/issues/316#issuecomment-379186790
The system expects the 4 player sign in UI to show up and then be submitted, but Xenia did not send an XNotify confirming that had happened, so the title behaves as if the UI had been closed. 
Example of expected behavior on a real console (see 3:35):
https://www.youtube.com/watch?v=nHkzTpqnNRM
I am not sure if any other titles are impacted.

[XAM] XamShowSigninUI: Fix issue with loading profile(s)

---

src/xenia/kernel/xthread.cc
src/xenia/kernel/xthread.h

<Naming still to decide, suggestions are welcome 🐑 >
It seems like actual thread stack allocation location is not valid
After spending a while why it fixed Nier it seems like Nier overwrites actual thread stack space with it's own data.
I spent while checking if it affects other games (around 30+ titles). It looks like it's not, but as we can see some games might be affected.

[Kernel/Thread] Changed default stack location

---

tools/build/scripts/test_suite.lua

Disable Edit and Continue for test suites. Edit and Continue in MSVC can cause the `__LINE__` macro to produce invalid values, which breaks the usability of Catch2 output on failed tests.

Disable Edit and Continue for test suites.

---

src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc
src/xenia/kernel/xiocompletion.cc

By merging https://github.com/xenia-project/xenia/pull/1726 we introduced regression in at least 2 titles.
The case is that ``NtRemoveIoCompletion`` and ``NtSetIoCompletion`` are executed so frequently between 2 threads (iirc) that they run apart at some point what causes subthread that execute ``NtRemoveIoCompletion`` to run before main thread does ``NtSetIoCompletion`` and that causes lock.
I haven't found proper solution, however returning X_STATUS_SUCCESS instead of X_STATUS_TIMEOUT did a really nice trick.
I added note describing wth is going on just in case.
I also added these functions to high frequency one as in Monster High it can create 10gb log in around a minute. Which seems quite sketchy, but might be understanable. In WET they're using it to provide player movement (LOL) …

[Kernel/IO] IoCompletion: Removed !wait_ticks check

---

src/xenia/config.cc

Since cpptoml appears to be dead I tried fixing #1419 by detecting and skipping a UTF-8 BOM before parsing the config file.

[Core] Fix reading UTF-8 BOM config files

---

src/xenia/base/cvar.cc
src/xenia/base/logging.cc
src/xenia/base/logging.h
src/xenia/base/main_win.cc

This pull request aims to fix issue #1445  .  The cause of this issue is that the PrintHelpAndExit function was only writing to stdout out instead of notifying the user via a Message Box or something similar. 
This function gets called under two circumstances.
1.) The user gave the --help argument to Xenia. 
2.) The user gave invalid launch options to Xenia.
In order to differentiate between these cases, a boolean was added as an input to the function. This allowed me to put in a different message box for each of these cases. The --help message box displays the usage information, and the invalid argument message box tells the user that they gave invalid launch options then displays the usage information. 
This is my first pull request to this project, so hopefully everything follows the …

Invalid launch options no longer cause Xenia to exit silently

---

src/xenia/base/main_posix.cc
src/xenia/base/system.h
src/xenia/base/system_linux.cc

Use SDL for message boxes.
Loads SDL dynamically so we don't depend on it in `xenia-base`

[Base] Implement message boxes on Linux

---

src/xenia/kernel/xenumerator.cc

[Kernel] Fix `XStaticUntypedEnumerator` not tracking item count.
Somehow this didn't make it into PR #1862.

[Kernel] Fix XStaticUntypedEnumerator item count.

---

tools/build/scripts/pkg_config.lua

Fix pkg-config trailing space causing premake to output an extra empty library -l statement
Fixes #1868

[Linux] Fix pkg-config trailing space

---

src/xenia/kernel/xam/xam_content.cc

[XAM] Fix xeXamContentCreate to pass copy of root_name for deferred
operation, as the pointer may no longer be valid when the callback
is executed.

[XAM] Fix ContentCreate to pass copy of root_name.

---

src/xenia/base/string_util.h

The fpfs function is using strtof to convert a string to floating point
value, but the type may be a double. Using strtof in that case won't
provide enough precision, so switch to using strtod. When the type is a
float, the double will be down-converted to the correct value.

[Base] Fix fpfs with GCC/Clang

---

src/xenia/kernel/xam/apps/xlivebase_app.cc

Based on PGR4 code
Seems like ``XMsginProcessCall`` returns some internal code
I tried to use this: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/87fba13e-bf06-450e-83b1-9241dc81e781 to figure out what is correct message structure and define it correctly, but I had bad luck with it.
This fixes crash in PGR4 and Rainbow Six Vegas 2

[XAM] Return correct error code from GetServiceInfo

---

src/xenia/app/xenia_main.cc
src/xenia/emulator.cc
src/xenia/kernel/xam/xam_task.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_io_info.cc
src/xenia/vfs/devices/null_device.cc
src/xenia/vfs/devices/null_device.h
src/xenia/vfs/devices/null_entry.cc
src/xenia/vfs/devices/null_entry.h
src/xenia/vfs/devices/null_file.cc
src/xenia/vfs/devices/null_file.h

(This is mostly the same as #1740, cleaned up a little & without the CriticalRegion stuff that was merged in with #1849, made this separate since that PR has some info I didn't want to delete)
With this PR the **XMountUtilityDrive** function statically-linked into games will hopefully always return success, which should help with games that use that function to test HDD availability (eg. all the Halo games)
This is mostly done with workarounds though, as the linked-in code seems to include nearly a whole filesystem implementation inside it AFAIK, using things like the Stfs* kernel functions that we don't currently handle.
Fortunately we can just return some status codes that the utility drive code expects instead, and let it think that the cache0:/cache1:/cache: symlinks were created by …

[VFS/Kernel] Improved cache partition support via XMountUtilityDrive workarounds

---

src/xenia/kernel/kernel_state.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_module.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_module.h

This is based on clues inside freestyledash code (Thanks 💃)
This resolve one of reasons why custom dashes usually cannot run.
PS. I'm not sure about one thing. Does maximal path length on xbox matches defined _MAX_PATH? (and the alignment 🤷‍♂️)

[Kernel] Implemented ExLoadedImageName

---

src/xenia/base/cvar.h

Suggested by @gibbed.
`std::to_string` may print floating-point numbers with a comma instead of a period on some locales (Russian, French) at least on Linux, which makes cpptoml fail to parse the previously generated config, and Xenia fails to start for the second time. `fmt::format` seems not to have such an issue (at least for the default format, without modifiers).
cpptoml tries to convert commas to periods, but that's not taken into account in overall value parsing — while looking for the end of the value, cpptoml only, in particular, checks if the character is not a period, but a comma is treated as an unidentified trailing character.
This change interacts with cpptoml and effects only config file writing, but doesn't change anything in cpptoml's logic, so compatibility of old …

[Config] Use locale-neutral fmt instead of to_string

---

src/xenia/base/memory.cc
src/xenia/gpu/render_target_cache.cc
src/xenia/gpu/render_target_cache.h

- Replace the GCC aggressive loop optimization bug workaround by a more sane version
- Remove anonymous union and struct in RenderTargetKey (Conflicts with explicit constructor when using GCC). This also adds index sanitizing.

Fix gcc builds

---

src/xenia/app/emulator_window.cc

Removes a trailing slash from the URL

Fix "404 not found" on "Build commit on Github..."

---

src/xenia/cpu/backend/x64/x64_op.h
src/xenia/gpu/command_processor.h
src/xenia/gpu/d3d12/d3d12_render_target_cache.h
src/xenia/gpu/d3d12/texture_cache.h
src/xenia/gpu/draw_util.h
src/xenia/gpu/dxbc_shader_translator.h
src/xenia/gpu/primitive_processor.h
src/xenia/gpu/registers.h
src/xenia/gpu/render_target_cache.h
src/xenia/gpu/ucode.h
src/xenia/gpu/vulkan/texture_cache.h
src/xenia/gpu/xenos.h
src/xenia/kernel/util/xex2_info.h
src/xenia/kernel/xam/user_profile.h
src/xenia/kernel/xnotifylistener.cc
src/xenia/kernel/xnotifylistener.h
src/xenia/memory.h
src/xenia/vfs/devices/stfs_xbox.h

Unions of bit fields and underlying storage (which may need to have unused bits set to a deterministic value, such as 0, for use as a lookup key or to avoid leaking data) now always have the storage type specified as the first element. Previously this was inconsistent (the underlying type was the last mostly just in my code). Though most of my assumptions about the order turned out not to match the reality, this makes it harder to accidentally initialize a bit field union as `{field1, field2, …}`, which would leave the unused bits undefined.
`= 0` defaults for the underlying types are not used anymore, as they're misleading. There have been cases when I assumed that this would result in zeroing of unused bits when you have a constructor that sets up individual fields using an initializer …

[Code] Make union usage more consistent

---

src/xenia/kernel/xboxkrnl/xboxkrnl_rtl.cc

Additionally added check for highest possible month day
Source: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtltimefieldstotime (like from above implementation in Xenia)
``Month
Specifies a value from 1 to 12.`` but we had it up to 11 only.
https://github.com/xenia-project/game-compatibility/issues/29 - Resolves: Xbox live connection lost error

[Kernel] Added missing month to RtlTimeFieldsToTime

---

src/xenia/cpu/backend/x64/x64_emitter.h

Just checking if the resulting mask is non-zero means we cannot allow this function to check for multiple features in parallel. A hypothetical computer that supports FMA but not AVX2 will return `true` if you try to call `IsFeatureEnabled(kX64EmitFMA | kX64EmitAVX2)`. We should make sure all the masked flags return `true` rather than check for non-zero.
This is ramping up to allow for particular subsets of AVX512 to be checked for in parallel with a single function call.

[x64] IsFeatureEnabled: Allow parallel feature checks

---

src/xenia/base/arena.cc
src/xenia/base/arena.h
src/xenia/base/literals.h
src/xenia/base/logging.cc
src/xenia/base/string_buffer.cc
src/xenia/base/testing/threading_test.cc
src/xenia/base/threading.h
src/xenia/cpu/backend/x64/x64_code_cache.cc
src/xenia/cpu/backend/x64/x64_emitter.cc
src/xenia/cpu/ppc/testing/ppc_testing_main.cc
src/xenia/cpu/processor.cc
src/xenia/emulator.cc
src/xenia/gpu/d3d12/deferred_command_list.h
src/xenia/gpu/vulkan/texture_cache.cc
src/xenia/gpu/vulkan/vulkan_command_processor.cc
src/xenia/kernel/xthread.cc
src/xenia/ui/graphics_upload_buffer_pool.h
src/xenia/vfs/devices/disc_image_device.cc
src/xenia/vfs/vfs_dump.cc

Rather than using `n * 1024 * 1024`, this adds a convenient `_MiB`/`_KiB` user-literal to the new `literals.h` header to concisely describe units of memory in a much more readable way. Any other useful literals can be added to this header. These literals exist in the `xe::literals` namespace so they are opt-in, similar to `std::chrono` literals, and require a `using namespace xe::literals` statement to utilize it within the current scope.
I've done a pass through the codebase to replace trivial instances of `1024 * 1024 * ...` expressions being used but avoided anything that added additional casting complexity from `size_t` to `uint32_t` and such to keep this commit concise.

[Base] Add user-literals for several memory sizes

---

src/xenia/cpu/backend/x64/x64_emitter.cc
src/xenia/cpu/backend/x64/x64_emitter.h

Implements the detection of some baseline `AVX512` subsets and some common aliases into `X64EmitterFeatureFlags`.
So far, `AVX512{F,VL,BW,DQ}` are the only subsets of `AVX512` that are detected with this PR since I anticipate these are the ones that will actually be used a lot in the x64 backend. Some aliases are also implemented such as `kX64EmitAVX512Ortho` which is `AVX512F` and `AVX512VL` combined which are the two subsets of AVX512 required to allow for `AVX512` operations upon `ymm` and `xmm` registers.
These aliases can possibly be collapsed since we could just always require `AVX512VL` to be supported to allow for _any_ kind of `AVX512` to be used since we will practically always want to use `AVX512` on `xmm` registers at the very least as there is no use-case where we want to use …

[x64] Add `kX64EmitAVX512*` feature-flags

---

src/xenia/base/string_util.h
src/xenia/base/vec128.cc
src/xenia/base/vec128.h

This allows `catch` to print out the contents of a particular vector when diagnosing how a `REQUIRE` expression has failed.
Before:
After:
Also fixes an indexing issue in `string_util::to_hex_string`

[Base] Add operator<< string conversion for vec128_t

---

.appveyor.yml

```
Remove unneeded init:
As far as I can tell this is a leftover from the appveyor.yml Reference: https://www.appveyor.com/docs/appveyor-yml/
Cleanup command blocks:
cmd is the default shell, so it doesn't have to be specified.
Use proper multi-line syntax for install.
Make configuration into one line:
This reduces line count, but is mainly personal preference.
```

[AppVeyor] Cleanup

---

src/xenia/kernel/xam/apps/xmp_app.cc
src/xenia/kernel/xam/apps/xmp_app.h

By fixing notification masks in commit: https://github.com/xenia-project/xenia/commit/fdec0ab332736b5d61f493649b83b1cbd239efd6 we accidentally broke few games.
Based on [4B4E0806](https://github.com/xenia-project/game-compatibility/issues/1621) I removed ``XMPStop`` from ``XMPSetPlaybackController`` responsibilities as it seems to be incorrect and causes game to get confused when it switches between playback clients. 
However [45410813](https://github.com/xenia-project/game-compatibility/issues/147) still had broken player. After spending some time debugging game and behaviour on console I figured out that ``locked`` in playback isn't locked, but it defines what have playback rights. Is it embedded media player or title itself. By changing that and provided notification state I managed to …

[Kernel/XMP] Fixed notification regression

---

src/xenia/kernel/xboxkrnl/xboxkrnl_threading.cc

[xboxkrnl] `ExAcquireReadWriteLockExclusive` fixes:
- Don't unnecessarily double-load lock count.
- Don't release spin lock before we're done with the lock.
[xboxkrnl] `ExReleaseReadWriteLock` fixes:
- Don't unncessarily double-load lock members.
- Reset readers entry count when lock count becomes negative.
- Properly decrease writers waiting count when writer event fired.
[xboxkrnl] Implement `ExTryToAcquireReadWriteLockExclusive`.
[xboxkrnl] Implement `ExAcquireReadWriteLockShared`.
[xboxknrl] Implement `ExTryToAcquireReadWriteLockShared`.

X_ERWLOCK fixes

---

src/xenia/cpu/backend/x64/x64_sequences.cc

This addresses a JIT-issue in the case that the `src1` and `dest`
register are both the same. This issue only happens in the "generic"
x86 path but not in the BMI1-accelerated path.
Thanks Rick for the extensive debugging help.
When `src1` and `dest` were the same, then the `addc` instruction at
`82099A08` in title `584108FF` might emit the following assembly:
```
.text:82099A08                 andc      r11, r10, r11
|
| Jitted
|
V
00000000A0011B15  mov         rbx,r10
00000000A0011B18  not         rbx
00000000A0011B1B  and         rbx,rbx
```
This was due to the src1 operand and the destination register being the
same, which used to call the "else" case in the x64 emitter when it
needs to be handled explicitly due to register aliasing/allocation.
Addresses issue #1945

[x64] Explicitly handle AND_NOT `dest == src1`

---

src/xenia/cpu/backend/x64/x64_backend.cc
src/xenia/cpu/backend/x64/x64_backend.h
src/xenia/cpu/backend/x64/x64_emitter.cc
src/xenia/cpu/backend/x64/x64_emitter.h
src/xenia/cpu/ppc/testing/ppc_testing_main.cc

Rather than having a single bool to conditionally detect haswell-level
instruction features. The granularity is increased with a new
`x64_extension_mask` where individual features within the x64 backend
can be turned on or off in a bit-mask manner. Since we have an ARM
backend on the horizon, I've added this to the new `x64`
configuration-group rather than `CPU`. This new pattern will hopefully
allow for testing to be more targetted to certain processor features and
allows the user to determine if they want certain features to be enabled
or disabled(such as avoiding BMI2 on certain AMD processors due to
pdep/pext being incredibly slow). The default configuration is to allow
for haswell-level features, to recreate the fact that the default
configuration for `use_haswell_instructions` is …

[CPU] Remove `use_haswell_instructions` in favor of `x64_extension_mask`

---

src/xenia/hid/winkey/winkey_binding_table.inc
src/xenia/hid/winkey/winkey_input_driver.cc
src/xenia/hid/winkey/winkey_input_driver.h

This pull request makes it possible to rebind the keyboard controls in the xenia config file. This fixes #1333.
It supports switching layers using caps lock (as the current default key bindings) and multiple keys for the same gamepad input.
I acknowledge that the syntax is a bit awkward, and I would be happy to get some feedback on how I can improve it while maintaining compatibility with xenia's current key bindings.
As it stands, the syntax works like this:
`keybind_a = "0xBA"`      # binds key code 0xBA to the A button
`keybind_b = "'X'" `     # binds the X key to the B button. Chars are indicated by `'` as per C convention.
`keybind_a = "0xBA"`      # binds key code 0xBA to the A button
`keybind_right_trigger = "'E' 'O'"`      # binds both keys E and O to the right trigger. Space is …

Rebindable keyboard controls

---

src/xenia/ui/windowed_app_main_posix.cc

This adds a workaround to make Xenia use Xwayland when creating a GTK window using Wayland, instead of creating a Wayland window and then triggering an `assert` in the code.
I contributed pretty much the same change to ares a while back: https://github.com/ares-emulator/ares/pull/9
Please note that I only made sure that Xenia starts properly with this change. I can't test any further due to this system not having a fully Vulkan-compatible driver.
Closes https://github.com/xenia-project/xenia/issues/1936

[UI] Force use of Xwayland when running on Wayland

---

src/xenia/cpu/backend/x64/x64_emitter.cc

Rather than having a huge list of if-statements that all do the same
thing, this preprocessor allows a more concise pattern to detecting if
the emit-flag is enabled as well as the correlated Xbyak flag that it
needs to check for to before allowing the feature-flag to be emitted.
Also moved the AVX-check to the beginning to early-out rather than do a
bunch of wasted work only to find out last that the host doesn't even
support AVX.

[x64] Add host-extension detection preprocessor

---

src/xenia/app/emulator_window.cc

Save states are broken (#665) and swapping discs isn't supported so all these do is cause crashes.

[App] Disable stuff that crashes the emulator

---

src/xenia/cpu/backend/x64/x64_seq_vector.cc
src/xenia/cpu/testing/vector_shl_test.cc
src/xenia/cpu/testing/vector_shr_test.cc

In the `Int8` case of `VECTOR_SH{R,L}_V128`, when all the values are the
same, then a single-instruction `gf2p8affineqb` can be emitted that does
an int8-based arithmetic-shift, utilizing GF(8) arithmetic.
More info here:
https://wunkolo.github.io/post/2020/11/gf2p8affineqb-int8-shifting/
Also fixes the iteration-type for when detecting if all of the simd
lanes are the same value(was iterating `u16` and not `u8`).
Also adds some tests for these cases

[x64] Add `GFNI`-based optimization for `VECTOR_SH{R,L}_V128(Int8)` and tests

---

src/xenia/cpu/cpu_flags.cc
src/xenia/cpu/cpu_flags.h
src/xenia/cpu/ppc/ppc_emit_control.cc

Adds the PVR opcode to the list of recognized opcodes. Includes useful comments.
***Revival of #1464 (deleted fork)***

[Kernel] Add PVR opcode (includes cvars support)

---

xenia-build

Don't recursively init/update submodules.
When recursive fetching is desireable, set `fetchRecurseSubmodules = true` in `.gitmodules` for the relevant submodule.

Don't recursively init/update submodules.

---

src/xenia/base/console_app_main_win.cc
src/xenia/base/console_win.cc

This prevents subapps from crashing when executing wmain specific functions

[Base] Changed entry point to wmain for Windows

---

src/xenia/cpu/backend/x64/x64_emitter.cc

We only tested for BMI1 but not for BMI2, so we've been missing out on
BMI2 performance gains for a little while. Oops.

[x64] Fix missing BMI2 emit-feature detection

---

src/xenia/cpu/backend/x64/x64_emitter.cc
src/xenia/cpu/backend/x64/x64_emitter.h
src/xenia/cpu/backend/x64/x64_sequences.cc

Improving vrefp accuracy is especially important for 5454082B as it fixes:
- Grass flickering
- Cactus collision
- Random events (bandits, "pls help me", ...)
- Camp spawning
- Horse spawning
That particular title was affected at load time. The objects where probably loaded incorrectly into memory, vrefp was not involved in those issues once in-game.

Improve vrefp & vrsqrtefp accuracy

---

src/xenia/base/filesystem_wildcard.cc
src/xenia/base/filesystem_wildcard.h

TLDR:
This resolves such situation:
Provided pattern: ``abc.file``
Files in directory: ``aaabc.file, abc.file``
Actual behavior:
Returned file is: ``aabc.file``
Expected Behavior: 
Returned file is: ``abc.file``
This resolves:
https://github.com/xenia-project/game-compatibility/issues/480 - Requirement for protect_zero (was loading incorrect shader files)
https://github.com/xenia-project/game-compatibility/issues/1650 - Wasn't booting at all

[Wildcard] Match exact string if it doesn't contain any pattern

---

.drone.star
src/xenia/app/xenia_main.cc
src/xenia/apu/audio_system.cc
src/xenia/apu/xma_decoder.cc
src/xenia/base/delay_scheduler.cc
src/xenia/base/delay_scheduler.h
src/xenia/base/logging.cc
src/xenia/base/socket_win.cc
src/xenia/base/testing/threading_test.cc
src/xenia/base/threading_posix.cc
src/xenia/base/threading_win.cc
src/xenia/gpu/command_processor.cc
src/xenia/gpu/d3d12/pipeline_cache.cc
src/xenia/gpu/trace_player.cc
src/xenia/kernel/util/shim_utils.h
src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_ob.cc
src/xenia/kernel/xboxkrnl/xboxkrnl_threading.cc
src/xenia/kernel/xevent.cc
src/xenia/kernel/xfile.cc
src/xenia/kernel/xiocompletion.cc
src/xenia/kernel/xmutant.cc
src/xenia/kernel/xnotifylistener.cc
src/xenia/kernel/xobject.cc
src/xenia/kernel/xsemaphore.cc
src/xenia/kernel/xsemaphore.h
src/xenia/kernel/xsymboliclink.cc
src/xenia/kernel/xthread.cc
src/xenia/kernel/xtimer.cc

~~Fixes #1678~~ (there are other pending issues with the posix threading code) 
In the general scope of #1430 
This is an attempt to fix the spurious Linux CI fails we are seeing.
I mainly attribute them to the misuse of `cond_.notify_one()` (see #1678)
Additionally I replaced a lot of `Sleep` calls used for synchronisation with spin waits because timing is very unreliable on CI due to heavy over-provisioning.

Fix posix threading stuff 😿

---

src/xenia/cpu/backend/x64/x64_seq_vector.cc

`pxor` is a zero-uop register-rename and `gf2p8affineqb dest, zero, int8`
is a very quick single-instruction way to use affine galois
transformations to fill a register with an immediate byte without
touching memory.

[x64] Add GFNI optimization for SPLAT(int8)

---

src/xenia/gpu/shader_interpreter.cc

Was failing to build on Linux, This PR adds "#include <cfloat>" to fix it.

Add #include <cfloat> to fix build error on Linux.

---

src/xenia/cpu/backend/x64/x64_sequences.cc

Passes unit tests on my i9-11900k.
Just a single-instruction implementation of bitwise-not with no memory dependency.

[x64] Add AVX512 optimization for `NOT_V128`

---

src/xenia/cpu/ppc/testing/ppc_testing_main.cc

This was still using printf-style format specifiers. Causing memory
asserts to show up like this while testing.
```
!> 0000438C Memory 10001040 assert failed:
!> 0000438C   Expected: %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X
!> 0000438C     Actual: %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X
!> 0000438C     TEST FAILED
```
Updated them so they format correctly:
```
!> 00002CCC Memory 10001040 assert failed:
!> 00002CCC   Expected: FC FD FE FF 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
!> 00002CCC     Actual: FC FD FE FF 00 00 00 00 00 00 00 00 00 00 00 00
!> 00002CCC     TEST FAILED
```

[PPC] Fix memory assert formatting

---

src/xenia/cpu/backend/x64/x64_backend.cc
src/xenia/cpu/backend/x64/x64_emitter.cc
src/xenia/cpu/backend/x64/x64_emitter.h
src/xenia/cpu/backend/x64/x64_seq_vector.cc

Uses the single-instruction AVX512 `vperm*` instructions to accelerate
the `INT8_TYPE` and `INT16_TYPE` permutation opcodes.
The `INT8_TYPE` is accelerated using `AVX512VBMI` subset of AVX512.
Available since Icelake(Intel) and Zen4(AMD).
Passes the current unit tests as well as the `instr__gen_vperm.s` unit tests from https://github.com/xenia-project/xenia/pull/1348

[x64] Add AVX512 optimizations for `PERMUTE_V128`

---

.drone.star

Disabling tests is bad but having a CI that fails on master every second time is worse

[CI, Drone] Disable HighResolutionTimer test cases

---

src/xenia/emulator.cc
src/xenia/kernel/kernel_state.cc
src/xenia/kernel/kernel_state.h
src/xenia/kernel/util/xdbf_utils.cc
src/xenia/kernel/util/xdbf_utils.h
src/xenia/kernel/xam/xam_user.cc

Full list of changes:
- Removed dummy achievement loading and provide real data.
- Added iterating achievements and their details on boot (with regards to selected user language).
- Load localized title information based on user selected language instead of defaulting to english.
- Created method to load XdbfGameData (Splitted into 2 for case if we want to provide from which module or not).
- Changed ``XdbfXstrHeader`` -> ``XdbfSectionHeader``.

[Kernel] Support for loading achievement data

---

third_party/fxaa/LICENSE

The License for the fxaa header dependency currently does not have a license included alongside the file; add the license file for the FXAA3_11.H file (BSD 3-Clause License)

added fxaa LICENSE file

---

src/xenia/cpu/compiler/passes/finalization_pass.cc

Related to: https://github.com/xenia-project/xenia/issues/1817
I've got title mentioned in this issue (https://github.com/xenia-project/game-compatibility/issues/245) and found out after hitting assertion and checking which function causes issues that indeed it is caused by lack of space for labels.
They have this huge routine in their code that causes this crash: 
I've decided that instead of increasing label_len it will be better to just use hexadecimal notation.

[CPU] Increase amount of possible labels used in FinalizationPass

---

src/xenia/cpu/backend/x64/x64_sequences.cc
src/xenia/cpu/backend/x64/x64_util.h

Accelerates these two data-types in particular since the F32 variant is not actually utilized by anything it seems.
Tested using `instr_gen_fsel.s` and `instr_gen_vsel.s` from #1348.
Adds the `x64_util.h` header that will later house other utility-functions for x64 instructions that include extra encoding bits like `vpternlog*`, `vcmp`, `vpcmp`, `vfixupimm*`, `vrange`, etc

[x64] Add AVX512 optimizations for `OPCODE_SELECT`{V128,F64}

---

src/xenia/kernel/kernel_state.cc

This fixes https://github.com/xenia-project/game-compatibility/issues/721 requirement for ``protect_zero = false`` and further random crashes

[Kernel/Thread] Set TLS slot to 0 while freeing

---

xenia-build

Utilizes `multiprocessing` to allow for multiple power-pc assembly tests to be generated in parallel.
Some results on my i9-11900k(8c/16t):
Before:
```
Measure-Command {.\xb gentests}
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 11
Milliseconds      : 200
Ticks             : 112007585
TotalDays         : 0.000129638408564815
TotalHours        : 0.00311132180555556
TotalMinutes      : 0.186679308333333
TotalSeconds      : 11.2007585
TotalMilliseconds : 11200.7585
```
After:
```
Measure-Command {.\xb gentests}
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 5
Milliseconds      : 426
Ticks             : 54265895
TotalDays         : 6.28077488425926E-05
TotalHours        : 0.00150738597222222
TotalMinutes      : …
```

[Build] Add parallel PPC test generation

---

src/xenia/cpu/ppc/ppc_emit_altivec.cc

I don't know of any title that utilizes this instruction, but I went ahead and implemented it for completeness.
Verified the implementation with `instr__gen_vaddcuw` from #1348. Can be grabbed with:
```
git checkout origin/gen_tests -- src\xenia\cpu\ppc\testing\*vaddcuw.s
```

[PPC] Implement `vaddcuw`

---

src/xenia/cpu/ppc/ppc_emit_altivec.cc

Other half of #2125. I don't know of any title that utilizes this instruction, but I went ahead and implemented it for completeness.
Verified the implementation with `instr__gen_vsubcuw` from #1348. Can be grabbed with:
```
git checkout origin/gen_tests -- src\xenia\cpu\ppc\testing\*vsubcuw.s
```

[PPC] Implement `vsubcuw`

---

src/xenia/cpu/backend/x64/x64_seq_vector.cc

AVX512 has native unsigned integer comparisons instructions, removing the need to XOR the most-significant-bit with a constant in memory to use the signed comparison instructions. These instructions only write to a k-mask register though and need an additional call to `vpmovm2*` to turn the mask-register into a vector-mask register.
As of Icelake:
`vpcmpu*` is all L3/T1
`vpmovm2d` is L1/T0.33
`vpmovm2{b,w}` is L3/T0.33
As of Zen4:
`vpcmpu*` is all L3/T0.50
`vpmovm2*` is all L1/T0.25

[x64] Add AVX512 optimizations for `OPCODE_VECTOR_COMPARE_UGT`(Integer)

---

src/xenia/kernel/xam/xam_info.cc

This function is mostly used by modules/plugins to ensure the correct title is running before patching the game.

[XAM] Implemented XamGetCurrentTitleId

---

src/xenia/base/filesystem_posix.cc

Partial fix for #2119. The path to the file was not being set on posix devices and was preventing fragment files from being opened.

[Base] Set the path for posix file info

---

src/xenia/base/filesystem_posix.cc

Partial fix for #2119. Filters out the . and .. directory entries on linux.

[Base] Filter out relative directories on linux

---

src/xenia/kernel/xam/xam_net.cc

I did a little bit of an oopsie back when I was implementing this function.
I also added check to prevent going over 64 entries (hardcoded in structure amount)
Thanks to Bo98 for pointing that out

[NET] NetDll___WSAFDIsSet: Fixed incorrect endianness of fd_count

---

src/xenia/cpu/hir/value.cc

In cpu/hir/value.cc in the Linux code we used to take the low 64 bits of the 128 bit result when we should take the high bits instead.

[LINUX/CPU] Fixed MulHi in value.cc for Linux systems.
