src/poly/string.cc, src/poly/string.h, src/xenia/kernel/fs/filesystem.cc, src/xenia/kernel/fs/filesystem.h
Implemented path normalization so relative paths can be correctly resolved.
Related to issue #96
=> Resolve relative file paths

src/xenia/kernel/fs/filesystem.cc
Rewritten the canonicalization path logic to better handle complex relative paths
=> Various fixes to resolving relative paths

src/poly/string.cc, src/poly/string.h, src/xenia/kernel/fs/entry.cc
Some more string manipulation fluff
=> Resolving entry names

src/poly/fs.cc, src/poly/fs.h, src/poly/sources.gypi, src/xenia/kernel/fs/devices/disc_image_entry.cc, src/xenia/kernel/fs/devices/disc_image_entry.h, src/xenia/kernel/fs/devices/stfs_container_entry.cc, src/xenia/kernel/fs/devices/stfs_container_entry.h, src/xenia/kernel/fs/filesystem.cc, src/xenia/kernel/fs/filesystem.h, src/xenia/kernel/fs/gdfx.cc, src/xenia/kernel/fs/gdfx.h, src/xenia/kernel/fs/stfs.cc, src/xenia/kernel/fs/stfs.h
Provides support for persistent wildcard file requests, as described in #96
Also moved CanonicalizePath into common code (poly::fs)
Note: there is still plenty of room for optimization
=> Support for wildcard queries

src/poly/fs.cc, src/poly/fs.h, src/xenia/kernel/fs/gdfx.cc, src/xenia/kernel/fs/stfs.cc
Fixed incorrect logic when checking at the end of the string - some of the names had an added null character
Removed case sensitivity
=> Adjustments to wildcard engine

xenia-build.py
Remove references to old Visual Studio versions as they are not
supported anymore.
=> Update build script

src/xenia/cpu/frontend/test/xe-cpu-ppc-test.cc
Protect the tests from those nasty illegal instruction exceptions
=> Protect PPC test with __try __except

src/xenia/kernel/objects/xkernel_module.cc, src/xenia/kernel/objects/xkernel_module.h, src/xenia/kernel/objects/xmodule.h, src/xenia/kernel/objects/xuser_module.cc, src/xenia/kernel/objects/xuser_module.h, src/xenia/kernel/util/xex2.cc, src/xenia/kernel/util/xex2.h, src/xenia/kernel/util/xex2_info.h, src/xenia/kernel/xboxkrnl_modules.cc
Reads the XEX's export table to find exports and stuff
=> XexGetProcedureAddress by proc name

src/xenia/cpu/backend/x64/x64_sequences.cc
=> Fix CNTLZ (I think)

src/xenia/kernel/xboxkrnl_modules.cc
Initializes user modules, loads CRT and whatever.
=> Initialize modules in XexLoadImage

src/xenia/ui/main_window.cc, src/xenia/ui/main_window.h, src/xenia/ui/menu_item.cc, src/xenia/ui/menu_item.h, src/xenia/ui/win32/win32_menu_item.cc, src/xenia/ui/win32/win32_menu_item.h, src/xenia/ui/win32/win32_window.cc, src/xenia/ui/win32/win32_window.h, src/xenia/ui/window.h
=> Setup UI menu code

src/xenia/cpu/backend/x64/x64_sequences.cc
=> Fix 8bit and 16bit mul instructions

src/xenia/cpu/backend/x64/x64_sequences.cc
Accidentally committed some unrelated code in permute but that works too
=> Clean up mul sub/mul add code and fix a minor bug in mulsub f64

src/xenia/apu/audio_system.cc, src/xenia/cpu/processor.cc
Bonus: Games now buzz the hell out of the speakers!
=> Increase audio worker thread and cpu interrupt thread stack size

src/xenia/kernel/objects/xthread.cc, src/xenia/kernel/xobject.cc, src/xenia/kernel/xobject.h, src/xenia/memory.cc
Also added uninitialized flag to XObject::SetNativePointer
=> Memory scribble flag

src/xenia/kernel/xam_info.cc, src/xenia/kernel/xboxkrnl_memory.cc, src/xenia/kernel/xboxkrnl_video.cc
Gets portal up to the point where it freezes initializing the audio system (cause of thread pcr+0x10C not being correct CPU id)
=> A few fixes for portal

src/xenia/kernel/xam_net.cc
Readability, added some struct definitions
Also NetDll_XNetGetTitleXnAddr returns a loopback address
=> Misc. changes in xam_net

src/xenia/cpu/backend/x64/x64_emitter.cc, src/xenia/cpu/backend/x64/x64_emitter.h, src/xenia/cpu/backend/x64/x64_sequences.cc, third_party/half/ChangeLog.txt, third_party/half/LICENSE.txt, third_party/half/README.txt, third_party/half/include/half.hpp
This code might be correct. Maybe.
=> Emulate PACK/UNPACK for non-F16C CPUs

libxenia.vcxproj
Remove Target Platform Version
=> Fix error compilation With VS 2015

src/xenia/kernel/object_table.cc, src/xenia/kernel/object_table.h, src/xenia/kernel/objects/xthread.cc, src/xenia/kernel/xboxkrnl_ob.cc
* Fixes The Walking Dead season 2 crashing early
=> Object Duplication Fix

src/xenia/kernel/objects/xevent.cc, src/xenia/kernel/objects/xevent.h, src/xenia/kernel/objects/xmutant.cc, src/xenia/kernel/objects/xmutant.h, src/xenia/kernel/objects/xsemaphore.cc, src/xenia/kernel/objects/xsemaphore.h, src/xenia/kernel/objects/xthread.cc, src/xenia/kernel/objects/xthread.h, src/xenia/kernel/xboxkrnl_ob.cc, src/xenia/kernel/xobject.cc, src/xenia/kernel/xobject.h
* Fixes some games dereferencing part of the object header
* Duke Nukem
* Earthworm Jim
=> Misc. Kernel Object Fixes

src/xenia/ui/main_window.cc, src/xenia/ui/main_window.h, src/xenia/ui/win32/win32_window.cc, src/xenia/ui/win32/win32_window.h, src/xenia/ui/window.h
* Also adds the option to the window submenu
=> Fullscreen support with F6

src/xenia/base/clock.cc, src/xenia/base/string.cc
Here are some more include directives you're missing.
=> Fix additional includes

src/xenia/gpu/gl4/gl4_shader_translator.cc, src/xenia/gpu/gl4/gl4_shader_translator.h
Getting some good results with games that involve rigging with FLOW_CONTROL on.
Sonic Unleashed Demo: http://i.imgur.com/mndwqWd.jpg
=> GL4 Translator: ADDs/MULs/SUBs XZ instead of XY. Loops on FLOW_CONTROL.

src/xenia/base/byte_order.h, src/xenia/kernel/kernel_state.cc, src/xenia/kernel/objects/xmodule.cc, src/xenia/kernel/objects/xmodule.h, src/xenia/kernel/objects/xuser_module.cc, src/xenia/kernel/objects/xuser_module.h, src/xenia/kernel/util/xex2.cc, src/xenia/kernel/util/xex2.h, src/xenia/kernel/util/xex2_info.h, src/xenia/kernel/xam_info.cc, src/xenia/kernel/xboxkrnl_module.cc, src/xenia/kernel/xboxkrnl_modules.cc, src/xenia/kernel/xboxkrnl_rtl.cc, src/xenia/xbox.h
* Fixes anything that dereferences HMODULE (GetProcAddress is a big one)
=> Swap to using HMODULE instead of handles for xex modules.

src/xenia/kernel/xboxkrnl_rtl.cc
* Converted a few functions over to the new style
=> xbox kernel RTL cleanup

src/xenia/base/memory_generic.cc
Part of https://github.com/benvanik/xenia/issues/308
=> Use SSE intrinsics for uint16_t byte swapping

libxenia.vcxproj, libxenia.vcxproj.filters
=> Fix the natvis file name

src/xenia/kernel/objects/xuser_module.cc
=> Typecast xe::be before sending it into printf

src/xenia/cpu/xex_module.cc, src/xenia/cpu/xex_module.h, src/xenia/debug/debugger.cc, src/xenia/debug/debugger.h, src/xenia/emulator.cc, src/xenia/kernel/kernel_state.cc, src/xenia/kernel/kernel_state.h, src/xenia/kernel/objects/xmodule.cc, src/xenia/kernel/objects/xmodule.h, src/xenia/kernel/objects/xthread.cc, src/xenia/kernel/objects/xthread.h, src/xenia/kernel/objects/xuser_module.cc, src/xenia/kernel/objects/xuser_module.h, src/xenia/kernel/xam_info.cc, src/xenia/kernel/xam_module.cc, src/xenia/kernel/xam_module.h, src/xenia/kernel/xboxkrnl_io.cc, src/xenia/kernel/xboxkrnl_module.cc, src/xenia/kernel/xboxkrnl_modules.cc, src/xenia/kernel/xboxkrnl_threading.cc, src/xenia/xbox.h
* Now games can infinitely reload themselves!
* Makes valve games work (which use an app chooser and reload themselves when the user chooses a game)
=> Implement XamLoaderLaunchTitle/XamLoaderTerminateTitle

src/xenia/kernel/util/shim_utils.h, src/xenia/kernel/xam_net.cc, src/xenia/kernel/xboxkrnl_threading.cc
* Keeps BF 1943 (and possibly other frostbite games) from spamming the log on one of its threads
=> XAM WSA Events

compatibility.html
Only tested through the chrome console
=> Use an alternate method to retrieve box art

compatibility.html
=> Add generic box art when no art is found

compatibility.html
So sorry about this, it's been a train wreck. If this doesn't work I give up.
=> Fixed the generic image load

src/xenia/kernel/xboxkrnl_crypt.cc, third_party/crypto/TinySHA1.hpp
* Also stubbed some other functions
=> Implement xboxkrnl SHA-1 algorithm

src/xenia/debug/debugger.cc, src/xenia/gpu/gl4/gl4_shader.cc, src/xenia/kernel/kernel_state.cc, src/xenia/kernel/kernel_state.h, src/xenia/kernel/objects/xthread.cc, src/xenia/kernel/objects/xthread.h, src/xenia/kernel/xam_net.cc, src/xenia/kernel/xboxkrnl_modules.cc, src/xenia/kernel/xboxkrnl_rtl.cc, src/xenia/kernel/xobject.h, src/xenia/ui/window.h, src/xenia/ui/window_win.cc, src/xenia/ui/window_win.h, src/xenia/xbox.h
* Mostly cosmetic changes (but those help games run too, right?)
=> Misc fixes

src/xenia/kernel/objects/xfile.h, src/xenia/kernel/objects/xthread.cc, src/xenia/kernel/objects/xthread.h, src/xenia/kernel/util/shim_utils.h, src/xenia/kernel/xboxkrnl_io.cc, src/xenia/kernel/xboxkrnl_modules.cc, src/xenia/xbox.h
* Holy shit, minecraft now goes ingame with this! (xenia-project/game-compatibility#29) 
* Potential to fix other games that hung on loading screens (ones that monitor thread exit codes to signal load finished)
* Fixes BF1943 hang on loading screen
=> Minecraft fixes

src/xenia/kernel/xboxkrnl_io.cc
=> Couple of fixes for IO

src/xenia/apu/xma_context.cc, src/xenia/apu/xma_context.h, src/xenia/hid/winkey/winkey_input_driver.cc, src/xenia/kernel/objects/xenumerator.h, src/xenia/kernel/util/shim_utils.h, src/xenia/kernel/xam_content.cc, src/xenia/kernel/xam_info.cc, src/xenia/kernel/xam_ui.cc, src/xenia/kernel/xobject.cc, src/xenia/kernel/xobject.h, src/xenia/xbox.h
* Add keyboard input dialog
* Fix XamEnumerate infinite loop if called in while loop
* Other:
* Winkey support for right stick (on arrow keys) and GetKeystroke
=> XAM Misc Changes

src/xenia/kernel/xboxkrnl_threading.cc
=> Fix (to the best of my knowledge) InterlockedPopEntrySList

src/xenia/cpu/frontend/ppc_emit_altivec.cc
@benvanik You'll probably want to double check and make sure this works as intended.
=> vcmpbfp with Rc bit support

src/xenia/kernel/xam_net.cc
* Fixes L4D (and maybe other games with a listen server?)
=> NetDll_inet_addr needs to convert endianness!

src/xenia/apu/xma_context.cc, src/xenia/apu/xma_context.h
* Fixes L4D and other Valve games.
=> XMA can only decode entire frames at a time.

src/xenia/memory.cc
range
Fixes crash when loading SSX.
=> Fix crash in memory allocation when there is no space to fit entire page

src/xenia/apu/xma_context.cc, src/xenia/cpu/processor.cc, src/xenia/cpu/raw_module.cc, src/xenia/gpu/gl4/command_processor.cc, src/xenia/kernel/user_module.cc, src/xenia/kernel/util/shim_utils.h, src/xenia/kernel/util/xex2_info.h, src/xenia/kernel/xam/xam_content.cc, src/xenia/kernel/xboxkrnl/xboxkrnl_memory.cc, src/xenia/kernel/xboxkrnl/xboxkrnl_threading.cc, src/xenia/kernel/xthread.cc, src/xenia/kernel/xthread.h, src/xenia/xbox.h
* Uhh, too much to list!
* Should fix absolutely nothing
=> Misc changes

src/xenia/base/memory.h, src/xenia/base/memory_win.cc, src/xenia/cpu/mmio_handler.cc
* Fixes games that update writewatched memory on multiple threads (ex. BF1943)
=> Fix MMIO Handler Race Condition

src/xenia/kernel/xboxkrnl/xboxkrnl_memory.cc, src/xenia/kernel/xboxkrnl/xboxkrnl_threading.cc
* Implemented KeSetCurrentStackPointers
* Used by thread fibers, fixes a few games.
=> Kernel Stack Switching (KeSetCurrentStackPointers)

src/xenia/gpu/gl4/command_processor.cc
=> Rectangle List Fix (projection issues on right-aligned vertices)

src/xenia/cpu/backend/x64/x64_code_cache.cc, src/xenia/cpu/backend/x64/x64_code_cache.h, src/xenia/cpu/backend/x64/x64_emitter.cc, src/xenia/emulator.cc
* Not optimized, but shouldn't matter cause the indirection table is almost always available.
=> Indirection table fallback

src/xenia/gpu/gl4/gl4_shader_translator.cc, src/xenia/gpu/ucode_disassembler.cc
This fixes smooth-skinned models' animations in Legend of Spyro: Dawn of the Dragon (and maybe other Criware games? though I don't have any handy to test).
=> Shader relative constant fix

src/xenia/kernel/notify_listener.h, src/xenia/kernel/util/object_table.h, src/xenia/kernel/xenumerator.h, src/xenia/kernel/xevent.h, src/xenia/kernel/xfile.h, src/xenia/kernel/xmodule.h, src/xenia/kernel/xmutant.h, src/xenia/kernel/xsemaphore.h, src/xenia/kernel/xthread.h, src/xenia/kernel/xtimer.h
* Asserts if LookupObject would return an object that isn't of the requested type.
=> XObject Type Verification

src/xenia/gpu/gl4/draw_batcher.cc
* Fixes black screen in Banjo Kazooie
=> Disable GL_CULL_FACES when drawing rectangle lists

src/xenia/gpu/gl4/gl4_shader_translator.cc
dest.x = 1;
dest.y = src0.y * src1.y;
dest.z = src0.z;
dest.w = src1.w;
=> Fix distance vector

src/xenia/apu/premake5.lua, src/xenia/apu/xaudio2/premake5.lua, src/xenia/hid/xinput/premake5.lua
Please see commit message for details of the problem and fix.
Pull requets for the same problem will be created for the "libavutil" and "elemental-forms" projects.
=> Premake: Fix usage of build scripts

compatibility.html, styles/main.scss
Used jQuery and DataTables to quickly filter the table while the search is entered. Added a bit of CSS to pretty up the search input.
=> Simple filtering for Compatibility Tracker

src/xenia/cpu/frontend/ppc_emit_control.cc
* Fixes the WMV decoder among other things
=> Fix complemented CR logic instructions

src/xenia/app/xenia_main.cc
This PR adds support for automatically selecting the discrete GPU on laptops with combined Intel/Nvidia graphics.
I'm not entirely sure if this is the best place to put the exported variable, I'm happy to move it elsewhere if need be.
=> Nvidia Optimus support

src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc, src/xenia/kernel/xfile.cc, src/xenia/kernel/xfile.h
* Fixes NtReadFile/NtWriteFile not returning STATUS_PENDING when expected to do so.
=> Async IO Fix

src/xenia/base/debug_visualizers.natvis, src/xenia/base/vec128.h, src/xenia/cpu/backend/x64/x64_code_cache.h, src/xenia/cpu/backend/x64/x64_sequences.cc, src/xenia/cpu/compiler/passes/constant_propagation_pass.cc, src/xenia/cpu/cpu_flags.cc, src/xenia/cpu/cpu_flags.h, src/xenia/cpu/hir/hir_builder.cc, src/xenia/cpu/hir/hir_builder.h, src/xenia/cpu/hir/opcodes.h, src/xenia/cpu/hir/opcodes.inl, src/xenia/cpu/hir/value.cc, src/xenia/cpu/hir/value.h, src/xenia/cpu/ppc/ppc_context.h, src/xenia/cpu/ppc/ppc_emit_altivec.cc, src/xenia/cpu/ppc/ppc_emit_control.cc, src/xenia/cpu/ppc/ppc_emit_memory.cc, src/xenia/cpu/ppc/ppc_hir_builder.cc, src/xenia/cpu/ppc/ppc_hir_builder.h, src/xenia/cpu/xex_module.cc, src/xenia/gpu/glsl_shader_translator.cc, src/xenia/kernel/xboxkrnl/xboxkrnl_threading.cc
* Removed quite a few commonly hit emulated instructions
* PACK_TYPE_FLOAT16_3 (speculative, not confirmed by testing on 360 but seems to work ok-ish)
=> X64 Speedups

src/xenia/vfs/devices/disc_image_device.cc
Thanks to @TechnoCrunch for finding this
=> Fix an overflow crash in DiscImageDevice::Verify

src/xenia/gpu/gl4/gl4_shader.cc, src/xenia/gpu/gl4/gl4_shader.h, src/xenia/gpu/glsl_shader_translator.cc
* Also rewrote GL4 Shaders and stuff
=> Fix shaders reading 10_11_11 bitfields backwards.

src/xenia/gpu/gl4/draw_batcher.cc, src/xenia/gpu/gl4/draw_batcher.h, src/xenia/gpu/gl4/gl4_command_processor.cc, src/xenia/gpu/gl4/gl4_command_processor.h, src/xenia/gpu/gl4/gl4_trace_viewer_main.cc, src/xenia/gpu/trace_viewer.cc, src/xenia/gpu/trace_viewer.h
* Allows us to view vertex shader output.
=> GL TFB support

src/xenia/gpu/gl4/gl4_command_processor.cc, src/xenia/gpu/glsl_shader_translator.cc
* Depth clear wasn't working cause we weren't getting the depth target if it wasn't the source.
* Shaders:
* Fix 2_10_10_10 fetch being completely wrong (now only partially wrong)
* Runtime check for vertex fetch index
* Fix trying to make a vec1
=> Fix Depth Clear / few shader fixes

src/xenia/kernel/xboxkrnl/xboxkrnl_audio_xma.cc
=> XMAInitializeContext Stereo Audio Fix

src/xenia/base/ring_buffer.cc, src/xenia/base/ring_buffer.h, src/xenia/gpu/command_processor.cc, src/xenia/gpu/command_processor.h
* Hardens the command processor against malformed/unknown packets
* Signals an error on any unknown PM4 packets
* Size checks on other commands
=> Command Processor RingBuffer Replacement

src/xenia/gpu/glsl_shader_translator.cc, src/xenia/gpu/glsl_shader_translator.h
* Significantly reduces frametime on a bunch of games
* Mainly got some low hanging ones, still lots more to go.
* Parsing flow control into if blocks, for blocks, etc.
* Need to absolutely eliminate branching when possible.
* Switch statements generate a huge nest of if statements :|
=> GLSL Optimizations

src/xenia/gpu/graphics_system.cc, src/xenia/kernel/notify_listener.cc
Please see each commit for details, thanks!
=> Two small fixes

src/xenia/gpu/command_processor.cc, src/xenia/gpu/command_processor.h
* Adds some notes on vizquery to the command processor (for consideration when working on Vulkan backend)
* Implements PM4_SET_BIN_MASK/SELECT
=> Viz Query WIP Notes

src/xenia/gpu/spirv_shader_translator.cc
Fix Rcp/Rsq OpSelect incorrect usage
Added name info to constants
=> Couple Quick Fixes to SPV translator

src/xenia/emulator.cc, src/xenia/emulator.h, src/xenia/kernel/user_module.cc, src/xenia/kernel/util/gameinfo_utils.cc, src/xenia/kernel/util/gameinfo_utils.h
Added utility to parse game information and updated launch logic to use it.
Addresses Ben's comment in #529 until we can throw up error messages
=> Find correct launch module for XNA-based games

xb.bat
Probably not that important, but updating it anyway
=> Bump suggested Python 2.7 version in xb.bat

src/xenia/app/emulator_window.cc, src/xenia/app/emulator_window.h, src/xenia/ui/ui_event.h, src/xenia/ui/window.cc, src/xenia/ui/window.h, src/xenia/ui/window_listener.h, src/xenia/ui/window_win.cc
#614 
Adds the ability to drag and drop files from windows in order to attempt
to execute them
=> Add file drop functionality

src/xenia/kernel/xboxkrnl/xboxkrnl_audio.cc
I'm working on converting the kernel conventions, this is for xboxkrnl_audio, but I could put more into this PR or open up new PRs for each module
=> Updating kernel convention (xboxkrnl_audio.cc) (#631)

src/xenia/kernel/xboxkrnl/xboxkrnl_modules.cc
=> Update xboxkrnl_modules to new convention

src/xenia/vfs/devices/stfs_container_device.h
Closes #673 
(credit to @Margen67 for finding these)
=> vfs: fix a typo & dead link

.github/CONTRIBUTING.md, README.md, docs/building.md, xb.bat
All URLs should probably be updated to be https not http.
=> Move CONTRIBUTING.md to .github, update Python 2.7 to latest, & change Github releases link to Appveyor artifacts

src/xenia/kernel/xam/xam_info.cc, src/xenia/kernel/xam/xam_msg.cc, src/xenia/kernel/xam/xam_notify.cc, src/xenia/kernel/xboxkrnl/xboxkrnl_memory.cc, src/xenia/kernel/xboxkrnl/xboxkrnl_misc.cc
Hi, I hope I understood everything correctly. Feel free to add any comments and please be nitpicky :)
xam_info.cc
xam_msg.cc
xam_notify.cc
xboxkrnl_memory.cc
xboxkrnl_misc.cc
=> Update shim conversion on some files

src/xenia/app/emulator_window.cc, src/xenia/ui/ui_event.h, src/xenia/ui/window_win.cc
Attempt to fix #698 
Based on @DrChat feedback in #700, I've added the modifier key to KeyEvent.
=> Open file chooser on ctrl-O

about.md, faq.md, index.html
OpenGL no longer supported and faq; index pages; about fixed.
Fixed issue #723
=> Removed OpenGL add Vulkan support to faqs and index

about.md, development/quickstart.md, faq.md, index.html
@DrChat I see you deleted buildbot to change it from not displaying on index page what do I change? I see it in _config.yml not sure what that does though.
=> Fixed Gh-pages

src/xenia/kernel/xboxkrnl/xboxkrnl_strings.cc
Missing break statement in xboxkrnl_strings.cc
=> Missing break statement

src/xenia/cpu/ppc/ppc_emit_memory.cc
This fixes sonic adventures so it is now playable
=> [JIT] stmw/lmw

about.md
=> Fix broken link

faq.md
=> Fix more broken links

docs/building.md
THEY FINALLY GOT AROUND TO FIXING THE STUFF!
=> Move cmder.net over to HTTPS

docs/gpu.md
Minor change, this link didn't point to the right file, so I corrected it..
Well, it didn't point to any file really
=> Fixed link

src/xenia/gpu/command_processor.cc
Last two expression is always false because 'else if' condition matches the first condition
example: https://ideone.com/1PSj91
=> Fix for bit check in command_processor.cc

premake5.lua
Through changes in compile flags, games now run 3-4 fps faster. I also made a few changes so that we didn't have unnecessary returns on functions with static returns.
=> [optimizations] More fast

.appveyor.yml
=> [AppVeyor] Update to VS2019

.appveyor.yml
=> [AppVeyor] Use proper MSBuild version

src/xenia/cpu/hir/value.cc
Also little type adjustments for vavgsh
It also resolved assertion fault releted to this opcode
=> Added support for Altivec: vavgsb

.gitmodules, src/xenia/cpu/backend/x64/x64_assembler.cc, src/xenia/cpu/backend/x64/x64_backend.cc, src/xenia/debug/ui/debug_window.cc, third_party/capstone.lua
=> [third_party] Update capstone to latest stable (4.0.1)

src/xenia/kernel/xboxkrnl/xboxkrnl_crypt.cc
Fixes malfunctioning SHA256 hash, corrupting its state between Update and Finish calls.
**Some** code paths were performing byteswapping from host to guest endianness (`XeCryptSha256Init`), but some were not (`XeCryptSha256Update`, `XeCryptSha256Final`), so SHA256 object was left in a corrupted state and hashing yielded wrong results.
Huge thanks to @Gliniak who scanned the logs and identified SHA256 functions as a possible culprit - I'd spend hours looking into I/O functions otherwise :)
Makes Forza Horizon go ingame:
**Question:** I have similar doubts about DES3 where `XECRYPT_DES_STATE` contains `uint32_t`'s in host endianness, but it's a guest structure. However, I'm not sure what's their true data type - they're defined as
```
uint32_t keytab[16][2];
```
but the way DES3 uses those …
=> Fix SHA1 and SHA256 state endianness

src/xenia/app/emulator_window.cc, src/xenia/app/emulator_window.h
Allows the usage of F2 key to open current build commit in browser
=> Add F2 Hotkey to open current commit ID URL

src/xenia/base/threading_win.cc
This ticket makes `set_thread_name` call [`SetThreadDescription`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription) on Windows, which allows us to name threads so that other tools can retrieve those names.
This also allows the VS debugger to be able to retrieve thread names when attached to a process.
=> [Base] Call SetThreadDescription to name threads

src/xenia/kernel/xboxkrnl/xboxkrnl_ob.cc
From functional changes:
- Implemented situation when we can receive different object type in handle and object_type_ptr. It returns X_STATUS_OBJECT_TYPE_MISMATCH; (Which is based on [windows documentation](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-obreferenceobjectbyhandle))
from other changes: 
- Removed DRY code
- overall code simplification
Thanks to @CookiePLMonster for help and patience.
=> [Kernel] Rewrote ObReferenceObjectByHandle

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
Add wiki link to top since people don't (or can't) read it.
Change discord.me invite link back to normal discord.gg.
Change game-compatibility link to readme since people don't (or can't) read it.
Add Discord server link in config.yml.
=> Update to new issue template workflow

src/xenia/cpu/compiler/passes/register_allocation_pass.cc, src/xenia/cpu/compiler/passes/register_allocation_pass.h
- Deprecated in C++11
- Removed in C++17
=> Replace binary_function by plain function.

src/xenia/cpu/backend/x64/x64_sequences.cc
It seems vmsum3fp128/vmsum4fp128 need to output a NAN on overflow.
Do so. Probably inefficiently.
(Also, [theme song for this PR](https://youtu.be/Hci2kZ8DlJM).)
=> [x64] NAN up vmsum3fp128/vmsum4fp128.

Gemfile, _config.yml, _includes/page-footer.html, _readme.md, _sass/_layout.scss, about.md, index.html
You can see a preview here: https://margen67.github.io/xenia/
Closes #1204.
=> Minor changes

src/xenia/kernel/xam/xam_user.cc
[XAM] Add default case in xeXamUserReadProfileSettingsEx.
=> [XAM] Add default case in xeXamUserReadProfileSettingsEx to shut Travis up.

src/xenia/kernel/xam/xam_user.cc
[XAM] Fix xeXamUserReadProfileSettingsEx.
- Properly calculate initial buffer_offset.
- Don't set buffer_size_ptr when its initial value is non-zero.
=> [XAM] Fix xeXamUserReadProfileSettingsEx.

src/xenia/gpu/d3d12/pipeline_cache.cc
[D3D12] Properly setup shareable shader storage.
- Properly create shareable shader storage directory.
- Log errors when failing to create shareable shader storage directory or shareable shader files.
=> [D3D12] Properly setup shareable shader storage.

src/xenia/ui/d3d12/d3d12_immediate_drawer.cc, src/xenia/ui/imgui_drawer.cc, src/xenia/ui/vulkan/vulkan_immediate_drawer.cc
ImGui does not orientate triangles.
Culling must not be applied in immediate drawer.
Added ImGui style colors for things that weren't rendered before.
=> [ImGui] Fix drawing lines.

src/xenia/hid/input_system.cc
Keystrokes from multiple backends where mixed.
Effectively doubling all keystroke inputs.
=> [Input] Fix doubling with any enabled.

src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc, src/xenia/xbox.h
[Kernel] Reject IO for paths with invalid characters.
=> [Kernel] Reject IO for paths with invalid characters.

src/xenia/kernel/xam/xam_notify.cc
Really small change to XNotifyGetNext based on _Carcassonne_ game code.
PS. Game still gonna crash due to returning error code in _XUsbcamCreate_, but that will be in another PR, as I still don't know whole story 🦊
=> [Kernel/Xam] XNotifyGetNext - Check for null in id_ptr

src/xenia/kernel/xam/xam_user.cc
For Vigilante 8 Arcade crash on entering gameplay.
=> [XAM] Stub valid xuids usage xeXamUserReadProfileSettingsEx.

src/xenia/base/logging.cc, src/xenia/base/logging.h, src/xenia/base/main_win.cc
These two changes are only partially related so I can split them into two pull requests if needed (although the console window needs the multiple logging sinks code).
This PR supersedes https://github.com/xenia-project/xenia/pull/1424
=> [Base] Support multiple logging sinks and add support for a console window for logs

xenia-build
Usage:
`xb stub --class dir/class_name`
creates class_name{.h,.cc} at `src/xenia/dir/`
`xb stub --file dir/class.cc`
creates class.cc at `src/xenia/dir`
premake is automatically ran on successful file creation 
I am not very good at python so this can probably be improved and cleaned up
=> [Build] Add stub command for source file generation

xb.ps1
Provide a PowerShell script as an alternative to the cmd script.
This has not been extensively tested but on my local machine has fixed #1482
=> Add PowerShell build script as alternative to cmd

.appveyor.yml
Get rid of that stupid warnings in build logs.
=> [AppVeyor] Remove vcpkg.

src/xenia/kernel/xam/user_profile.h
It should fix games where right now there is no profile found.
Example: EA Sports games
=> [XAM/User] Added flag for local profile

src/xenia/kernel/xboxkrnl/xboxkrnl_memory.cc
Issue: https://github.com/xenia-project/xenia/issues/1558
We talked about it on discord, so I'm not gonna write essay here 💃 
Optional todo: Maybe remove some of the empty lines? I added them to increase readability, but maybe they're confusing 🤔
=> [Kernel] Zeroing out pages without write protect flag

src/xenia/gpu/shader_compiler_main.cc
=> Fix rvalue being passed as a reference.

premake5.lua, src/xenia/base/platform_win.h, src/xenia/kernel/xboxkrnl/xboxkrnl_crypt.cc
(E: saw this was linked at a few places, if you came here to get the Halo 3 debug build running you can see what's needed at https://github.com/xenia-project/game-compatibility/issues/178#issuecomment-751601895)
This implements the XeCryptBnQwNeRsaPubCrypt export via Windows BCrypt provider, this seemed like the easiest option for now to get this export working, since I wasn't too sure about trying to add in any other third-party crypto suites (it could be worth looking into though, since we're now including custom SHA1/SHA256/AES/RC4/DES & partial RSA, maybe there's a library somewhere that already implements all those for us?)
Getting this working with BCrypt was a pain, not a whole lot of documentation about using it with RSA on the net.. probably wasted an hour trying things with …
=> [Kernel] Implement XeCryptBnQwNeRsaPubCrypt via BCrypt (win32 only)

README.md
Changed the line to reference issue #1333 instead.
=> Reflect the closure of #60 in the README

src/xenia/kernel/xam/apps/xmp_app.cc
Fixes #1749 - didn't realize we had a main_thread() func to check if it's main thread or not, with that the fix for this was pretty simple, probably should have checked before making that issue...
MGS2 & MGS3 now both work fine, as if the Sleep(10) was never there.
I haven't tested with A-Train though but I'd guess it'll still let the looping thread mentioned in the comment Sleep. (If anyone is able to test A-Train it'd be interesting to see what happens if the Sleep is removed altogether, maybe after all this time it's no longer needed - would be great to get rid of it IMO)
E: is Appveyor having problems with the unit tests? In this PR the Checked tests failed, and in Gliniaks PR the Release tests also failed with the same check failing, weird.
=> [Kernel/XAM] Prevent Sleep from being used on main thread

src/xenia/kernel/xboxkrnl/xboxkrnl_memory.cc
Related to issue: #1667 
Most of the info is included in that issue (Including example code). I couldn't add such check when we're not providing ``*base_addr_ptr`` from obvious reason. However I wouldn't expect that to be such a big deal.
Note for testers please check if this PR causes any regression based on xenia: https://github.com/xenia-project/xenia/commit/ff5c5f01e0e31abee675be7e48c11c20642a40fb
Affected Titles:
- Serious Sam: TFE
- Perfect Dark Zero
=> [Kernel/Memory] Do not clear range if it was previously commited

src/xenia/apu/xma_decoder.cc
Was supposed to be warning and not error
https://discord.com/channels/308194948048486401/308207592482668545/824653795576381451
=> XMA: Set log level for unhandled register to warning

src/xenia/apu/xma_context.cc
That should resolve all of latest random host crashes in games 🐑
=> [APU/XMA] Prevent crash with invalid packet number

src/xenia/gpu/command_processor.cc
- Older D3D implementation used different flags
=> [GPU] Improve fake occlusion query compatibility

src/xenia/kernel/xam/xam_content.cc
This change is quite simple and self explanatory.
- Tenchu Z - Working Saves
=> [XAM] XamContentGetCreator check if package exists

src/xenia/base/logging.cc
- Ensure that logging waits until everything is written before shutting down.
- Fix a bug where a new log line would not be written until the next log line had been appended.
=> Logging fixes.

src/xenia/vfs/devices/host_path_file.cc
Fix `HostPathFile` access checks to additionally check generic access.
=> Fix HostPathFile access checks.

src/xenia/kernel/xam/apps/xgi_app.cc, src/xenia/kernel/xam/apps/xlivebase_app.cc, src/xenia/kernel/xam/xam_net.cc, src/xenia/kernel/xam/xam_user.cc
[kernel] 
Updated PR from Permanulled https://github.com/xenia-project/xenia/pull/1150/files#diff-358a33abb42660137d33300bbc8188c8R51
XGI messages to fix Jetpac XBLA
gets Aegis Wing, Jetpac, and MetalSlug 3 in game
=> [Kernel] XBLA Fixes

src/xenia/apu/xma_decoder.cc, src/xenia/apu/xma_decoder.h, src/xenia/apu/xma_register_file.cc, src/xenia/apu/xma_register_file.h, src/xenia/apu/xma_register_table.inc, src/xenia/base/byte_stream.cc, src/xenia/base/debug_visualizers.natvis, src/xenia/base/system.h, src/xenia/base/system_linux.cc, src/xenia/base/system_win.cc, src/xenia/cpu/hir/value.cc, src/xenia/cpu/ppc/ppc_emit_control.cc, src/xenia/cpu/ppc/ppc_frontend.cc, src/xenia/cpu/ppc/ppc_frontend.h, src/xenia/gpu/command_processor.cc, src/xenia/kernel/util/export_table_post.inc, src/xenia/kernel/util/export_table_pre.inc, src/xenia/kernel/util/ordinal_table_post.inc, src/xenia/kernel/util/ordinal_table_pre.inc, src/xenia/kernel/xam/xam_module_export_groups.inc, src/xenia/kernel/xam/xam_net.cc, src/xenia/kernel/xam/xam_table.inc, src/xenia/kernel/xbdm/xbdm_table.inc, src/xenia/kernel/xboxkrnl/xboxkrnl_error.cc, src/xenia/kernel/xboxkrnl/xboxkrnl_strings.cc, src/xenia/kernel/xboxkrnl/xboxkrnl_table.inc, src/xenia/vfs/virtual_file_system.cc, xenia-build
Finally getting around to pushing more of my local changes. 😃
=> Change rollup.

src/xenia/kernel/xboxkrnl/xboxkrnl_io.cc
This PR adds APC support to NtWriteFile, based on the APC code inside NtReadFile.
This is needed for some games when using mount_cache, such as Halo 4 and the Halo 3 Epsilon build, without it the game seems to get stuck waiting for something from the APC routine.
I've just copied over most of the body from NtReadFile here, which seems to work fine, but I'm not sure whether the code inside NtReadFile was just a temporary workaround or not... if it was maybe it'd be better to redo these properly instead.
(edit: again with travis issues :()
=> [Kernel] Add APC support to NtWriteFile

src/xenia/kernel/xam/apps/xam_app.cc, src/xenia/kernel/xam/xam_content.cc, src/xenia/kernel/xam/xam_content_aggregate.cc, src/xenia/kernel/xam/xam_content_device.cc, src/xenia/kernel/xam/xam_enum.cc, src/xenia/kernel/xam/xam_user.cc, src/xenia/kernel/xenumerator.cc, src/xenia/kernel/xenumerator.h, src/xenia/kernel/xobject.h
This should supersede #1812.
Infinite Undiscovery can do stuff now.
=> Enum and content fixes

src/xenia/cpu/backend/x64/x64_sequences.cc
Fix the the case where src1 is constant and src2 is non-constant causing
an assert due to trying to call `.constant()` on the src2 operand.
Interfaces with an issue Gliniak was encountering where title `4D53082D`
encounters an assert. Also includes a BMI1-acceleration in the 64-bit
case where a temporary register is needed(the `and` x86 instruction only
supports immediate constants up to 32-bits).
=> [x64] Fix OPCODE_AND_NOT src1-constant case

src/xenia/kernel/xboxkrnl/xboxkrnl_modules.cc
[xboxkrnl] Fix up `XexGetProcedureAddress` failure logging.
=> [xboxkrnl] Fix up XexGetProcedureAddress logging.

src/xenia/base/profiling.cc
Needs further fixing so it doesn't output on multiple lines, but this makes the output actually meaningful.
=> [Base] Fix MICROPROFILE_PRINTF.

src/xenia/base/memory.cc, src/xenia/base/testing/memory_test.cc
probably one of the last things on the priority list for an aarch64 port
=> [Base, aarch64] `copy_and_swap` implementations

src/xenia/kernel/xam/user_profile.h, src/xenia/kernel/xam/xam_user.cc
[XAM] Improvements to `XamUserReadProfileSettingsEx`/`XamUserWriteProfileSettings`.
- Unify `X_USER_READ_PROFILE_SETTING` and `X_USER_WRITE_PROFILE_SETTING` into `X_USER_PROFILE_SETTING`.
- Clean up `Setting` serialization to use `X_USER_PROFILE_SETTING_DATA` instead of manual buffer copying.
- Fix `XamUserReadProfileSettingsEx` case where `user_index` is non-zero and `xuids` are being used.
- Skip unset settings in `XamUserWriteProfileSettings_entry`.
=> [XAM] Improvements to XamUserReadProfileSettingsEx/XamUserWriteProfileSettings.

.drone.star, src/xenia/base/testing/memory_test.cc
Run `xenia-base-tests` with Valgrind.
Will mark this as ready once https://github.com/xenia-project/docker-buildenv/pull/3 is merged and available and I removed the last commit from this PR.
Also fix minor test issue
=> [CI] Valgrind tests

README.md
#1333 has been closed, so the README should reflect that, quite like we did in #1743.
This line can be replaced with another suggestion from the `good-first-issue` label, such as #1526.
=> Update README to Reflect Merged Changes

src/xenia/app/emulator_window.cc, src/xenia/app/emulator_window.h
[App] Rename `ShowCommitID` to `ShowBuildCommit`.
[App] Replace Website help menu item with FAQ.
[App] Add Compatibility help menu item.
=> Help improvements

tools/build/scripts/pkg_config.lua
Small enhancement when calling pkg-config on package that is not installed. This makes it easier to see what is missing and what to install!
Inspired by the [SDL2 premake helper](https://github.com/xenia-project/xenia/blob/6b45cf84472c26436d4a5db61a7b50dab301e398/third_party/SDL2.lua#L20).
=> Add descriptive error message when pkg-config fails

src/xenia/ui/file_picker_win.cc
Sets up Win32FilePicker for use with directories by doing the following:
- [Moves file type setup to an if statement](https://github.com/xenia-project/xenia/pull/1978/files#diff-6243c9f67471bef36087fa0192cbbd3f13fb77e9a9662b100990a4a504e3df0fR149-R169)
- [Adds one more if statement for `FOS_PICKFOLDERS` to be added to the flags.](https://github.com/xenia-project/xenia/pull/1978/files#diff-6243c9f67471bef36087fa0192cbbd3f13fb77e9a9662b100990a4a504e3df0fR141-R143)
Example from my [`mount-path-from-ui`](https://github.com/halotroop2288/xenia/tree/mount-path-from-ui) branch:
=> [UI] Implement Type::kDirectory in Win32FilePicker

.drone.star, xenia-build
Also disables some tests (see #2036) that depend on host scheduling timings, enhances error reporting of xenia-build and simplifies android target selection.
=> [CI] Use clang14 and Android ndk r25

src/xenia/cpu/backend/x64/x64_seq_vector.cc
[vcvttps2udq](https://www.laruence.com/x86/VCVTTPS2UDQ.html) already saturates overflowing and unordered values to `0xFFFFFFFF`. Using mask registers, zeroes are written to negative values within the same instruction.
The entire operation is just two instructions!
=> [x64] Add AVX512 optimization for `OPCODE_VECTOR_CONVERT_F2I`(unsigned)

src/xenia/cpu/backend/x64/x64_seq_vector.cc
Uses a single `vpternlogd` to test for signed/unsigned overflow/underflow. Then utilizes AVX512 mask operations to create either `0x7FFFFFFF` or `0x80000000` arithmetically.
=> [x64] Add AVX512 optimization for `OPCODE_VECTOR_ADD`(saturated)

.gitmodules
- Handle compiler flags per-file. Removes ffmpeg warnings
- Switch to JoelLinn fork since original author stopped maintaining and other forks don't seem to care about PRs
Please run 
```
git submodule sync
git submodule update
```
locally
=> [Premake] Update premake-cmake

src/xenia/cpu/backend/x64/x64_seq_vector.cc
Passes the `vsubuws` and `vsubsws` unit-tests from https://github.com/xenia-project/xenia/pull/1348
=> [x64] Add AVX512 optimization for `OPCODE_VECTOR_SUB`(saturated)

src/xenia/app/emulator_window.cc, src/xenia/debug/ui/debug_window.cc, src/xenia/gpu/trace_viewer.cc, src/xenia/ui/file_picker_win.cc, src/xenia/ui/imgui_drawer.cc, src/xenia/ui/imgui_drawer.h, third_party/imgui.lua
~~v1.88~~ v1.89 Has new table api which is quite useful.
Currently no access to Win machine so posting as draft until tested.
=> [ImGui] imgui v1.89

src/xenia/vfs/devices/stfs_container_device.cc, src/xenia/vfs/devices/stfs_xbox.h, src/xenia/vfs/premake5.lua, src/xenia/vfs/testing/premake5.lua, src/xenia/vfs/testing/vfs_test.cc
- Added test case for: decode_fat_timestamp
- Changed location of: decode_fat_timestamp
- Fixed invalid month decoding in decode_fat_timestamp
=> [Testing] Added test project for vfs
